### PR TITLE
Complemented navigation objects and extensions

### PR DESCRIPTION
**Pull request by teroarvola**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no

#### What's in this Pull Request?

Made possible to get and set navigation settings (inheritance and managed navigation related settings):

- Complemented AreaNavigationEntity with managed metadata related properties:
-- AddNewPagesToNavigation
-- CreateFriendlyUrlsForNewPages

- Complemented StructuralNavigationEntity wit property:
-- InheritFromParentWeb

- Complemented NavigationExtensions methods with getting and setting the above properties.

### CODE REVIEW

**Comment by jansenbe** [comment]
Looks good @teroarvola. I'll review and process this PR, thanks for your contribution. Can you also sign the CLA via https://cla.microsoft.com in case you've not yet done that in the past.

**Comment by jansenbe** [comment]
Hmm...merged your changes but the PR is not flipping to merged state. Guess GitHub still needs some more time to process it?

**Comment by jansenbe** [comment]
I merged from your navigationsettings branch whereas the PR was from the pnp_dev branch. Changes are the same, so we're good. Closing this PR now.

**Comment by teroarvola** [comment]
Thanks. I signed the CLA last week.

**Pull request closed without merging**
