### PR TITLE
GraphUtility class added with a function to invite a Guest user (Azure B2B)

### PR DESCRIPTION
**Pull request by vipulkelkar**
| Q               | A
| --------------- | ---
| Bug fix?        | 
| New feature?    | yes
| New sample?      | 
| Related issues?  | 

#### What's in this Pull Request?

Updated the **Microsoft.Graph** nuget package to the latest version. Added **GraphUtility** class to perform Graph operations using GraphServiceClient. 

Added a method to this class to invite guest user to tenant using Azure B2B Invitation API. This method can further be used to create a new command in PnP PowerShell to send user invite.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi @vipulkelkar, we'll process this asap.

**Comment by vipulkelkar** [comment]
Thanks @VesaJuvonen

**Comment by PaoloPia** [comment]
Hi @vipulkelkar,
Thanks for your effort. Before merging it I will double-check the proposed solution with the PnP Team, especially because you're updating a library (MSGraph client) that we use in many other places. Thanks.

**Comment by vipulkelkar** [comment]
Thanks Paolo. Yes, had that concern too. Looking forward to an update.

**Comment by vipulkelkar** [comment]
Hi @PaoloPia 
Any news on this ? Have another change in mind in the current UnifiedGroupsUtility class but that too needs a higher version of Graph client. Just wanted to check if there will be a higher GraphClient version available in PnP in the near future ?

**Comment by PaoloPia** [comment]
Hi @vipulkelkar,
I just upgraded the PnP Sites Core library to Microsoft Graph SDK v. 1.9.0. Do you mind re-submitting your PR targeting this latest version of the SDK? In the meantime, I will close this item. Thanks.

**Comment by vipulkelkar** [comment]
Hi @PaoloPia , i'll re-submit the change. Thanks

**Pull request closed without merging**
