### PR TITLE
Feature: Adds capability to connect existing team site to MS Teams team

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | NA

#### What's in this Pull Request?

This PR adds the capability to connect existing Modern team site to Microsoft team.
It will also work for classic sites which have been newly groupified because they have the RelatedGroupId property populated. 

Usage:

`var teamId = clientContext.TeamifyAsync().GetAwaiter().GetResult();`

or 

`var teamId = SiteCollection.TeamifySiteAsync(clientContext).GetAwaiter().GetResult();`

### CODE REVIEW

**Comment by wobba** [comment]
I'm pretty sure app-only works for this as I've done that in the past.

**Comment by gautamdsheth** [comment]
Hey @wobba , 

1) will double check the app-only thing.

2) I tried this on a communication site and it error-ed , giving group not found message. Any better way to handle it ? I think this API creates team for groupified sites which is handled by the RelatedGroupId check. We are not groupifying sites via this API, simply creating ms teams team for already groupified or modern team sites. I hope my understanding of the endpoint is correct, since there isn't much docs around it. If it's incorrect, can you please elaborate on it ? 

If we want to groupify sites, we already have 2 methods , via tenant extension and via rest API in the sitecollection.cs

**Comment by wobba** [comment]
Thinking if it's possible to get the group id if it's there somehow. Checking the webtemplate is just not 100% for knowing if it's a group or not.

**Comment by wobba** [comment]
@gautamdsheth You can check if `clientContext.Site.GroupId` is different from an empty guid if it's a group or not.

**Comment by gautamdsheth** [comment]
Gotcha, will update the PR in a bit.

**Comment by gautamdsheth** [comment]
hey @wobba , 

1) I was not able to get it working using the App-only method. 

Got the below error message:

```
System.Exception
  HResult=0x80131500
  Message={"odata.error":{"code":"10005","message":{"lang":"en-US","value":"Authentication method is not allowed."}}}
  Source=OfficeDevPnP.Core
  StackTrace:
   at OfficeDevPnP.Core.Utilities.RESTUtilities.<ExecutePost>d__2.MoveNext() in E:\PnP-Sites-Core-dev\PnP-Sites-Core-dev\Core\OfficeDevPnP.Core\Utilities\RESTUtilities.cs:line 189
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OfficeDevPnP.Core.Sites.SiteCollection.<TeamifySiteAsync>d__10.MoveNext() in E:\PnP-Sites-Core-dev\PnP-Sites-Core-dev\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line 655
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication3.Program.Main(String[] args) in E:\PnP-Sites-Core-dev\PnP-Sites-Core-dev\Core\ConsoleApp1\Program.cs:line 294

```

Can you check at your end again if you have some time ? 

2) Have updated the PR as per your comment about the GroupId property. 

Let me know your thoughts.

Cheers,
Gautam !

**Comment by wobba** [comment]
It needs `Group.ReadWrite.All`. Also mentioned in the docs https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0 and I have verified in a production tenant. Weird.

**Comment by gautamdsheth** [comment]
Hmm, I created the app using the SharePoint's app registration mechanism ( appregnew.aspx on the admin site collection ) and gave full control of the tenant, not via the Azure portal. But I guess that's not sufficient ? Do you think its a valid scenario worth checking in this method or we can skip this for now, i think we can skip it for now ? I have updated the PR to skip the check for now, but would love to know your thoughts :)

**Comment by wobba** [comment]
I'll merge and revisit later when we look closer at Graph commands 👍

**Pull request merged**
