### PR TITLE
List data extraction

### PR DESCRIPTION
**Pull request by czullu**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | https://github.com/SharePoint/PnP-Provisioning-Schema/issues/409, https://github.com/SharePoint/PnP-Provisioning-Schema/issues/412

#### What's in this Pull Request?
This pull request introduces the Parameters IncludeAllListContent and FilesToIgnore in ProvisionTemplateCreationInformation in order to activate Extract in ObjectListInstanceDataRows. For List Content Extraction to work, you need to have at least the Handlers Fields, ContentTypes and Lists active. If you need certain Files to be ignored you can add them to FilesToIgnore-List with web relative file-path i.e. “shared Documents/test.docx”

**Content Security:**
SharingLinks are ignore during extract.

**Limit List Content Extract:**
You can limit the Lists considered it by using the ListsToExtract Parameter in ProvisionTemplateCreationInformation providing "List-Tilte" or "List-Id" or "List-Web-relative-Url". 

**SitesPages Library:**
The SitePages Library is ignored  by the ObjectListInstanceDataRows Extract. PageContent Handlers are responsible for this.

**ContentTypes**
Certain ContentTypes come with Features - like for example DocumentSet. You need to make sure that you have them in the Template before you try to apply since otherwise it will fail. The Content Extraction does not take care of this dependency but if you active Features Handler you are save.

**List Attachments**
The List Attachments need Schema 201909. The Attachments are exported to path /[List Displayname]/[ItemId]/[FileName]. The Provisioning currently does always add Attachments to the List Item.

**Folder/DocumentSet** 
As of Schema 201909 Folders support ContentTypeId and Properties which will be Extracted. Provisioning sets the Folder Properties and if the ContentTypeId starts with 0x0120D520 the Folder will be converted to be a DocumentSet.

### CODE REVIEW

**Comment by czullu** [comment]
@PaoloPia I have added List-Attachment and Folder as DocumentSet Provisioning into this Pul request as im testing it togehter with extract/provision Schema 201909

**Comment by czullu** [comment]
@erwinvanhunen i have Folder to DocumentSet Provisioning as part of the code here and removed List Attachment Provisioing since i have seen your commit from yesterday

**Comment by jansenbe** [comment]
@czullu : thanks for this PR, @erwinvanhunen has been taking snippets of your code to built similar features, this really helps. The integration work is not yet finished, so let's keep this PR open until all is processed. In the meantime I've credited you in the changlog for the list item export work.

**Comment by jansenbe** [comment]
Hi @czullu , we're closing this PR as we've manually taken the needed pieces from it and credited you for it the changelog. Thanks again for this massive contribution!

**Pull request closed without merging**
