### PR TITLE
Assembly versioning change

### PR DESCRIPTION
**Pull request by jensotto**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
This pull requests proposes a change in the assembly versioning scheme. The current scheme makes it difficult to build extensibility handlers as they are required to target the exact same version as the provisioning engine runs. In addition prior to my pull request #1566 different referenced version would never give any warnings or errors to the user that the extensibility handler had not been run. With this PR and #1566 it should be much easier to build and maintain extensibility handlers over time.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @jensotto, we'll process this asap.

**Comment by jensotto** [comment]
I need to elaborate on one of the impacts this will have on how framework changes needs to be handled if this PR is approved.
It's vital that no breaking changes is introduced in any new releases within the same major version. This could lead to run time exceptions. If for instance a developer uses version 2.24.1803 (assembly file version)/2.24.0.0(assembly version) and uses an extension method named "A" the application throw a run time exception if the extension method is removed in the next minor or patch version (each monthly update has been minor version releases for the last 23 releases). This will of course only happen if the OfficeDevPnP.Core framework for some reason gets updated on the production environment. The reason for this is that in this PR the assembly version is identical for all releases except for major versions. In this example the next version would be 2.25.1804 (assembly file version)/2.24.0.0(assembly version). Note that the assembly version did not change. This is how strong-named Windows assemblies should be versioned as changing the assembly version will require the referencing code to be recompiled against the new version, unless binding redirects are used. Binding redirects might be impossible to use in this situation (for extensibility handlers). The only other option is to be smarter with assembly versioning so that only a major version release will change the assembly version.

My suggestion is nothing new. As an example this is how Microsoft does it for ALL the SharePoint assemblies, both server side and client side. The important thing is that changes needs to be more closely controlled and breaking changes must not be allowed unless changing the major version.

**Comment by jensotto** [comment]
I was a bit unfair with my example. I did not mention what would happen if the same situation happened with the current implementation. If a developer currently compiles against a version of OfficeDevPnP.Core and replaces the assembly with the next version there would also be a runtime exception, more specifically a assembly binding exception. This is the same that would happen if an extensibility handler targets a different assembly version than it runs under. So the new proposal makes run time exceptions less likely, but requires no breaking changes in the assembly without changing the assembly version, and according to semantic version it should only be done when changing the major version.

**Comment by wobba** [comment]
The current version schema is date based, and PnP is always built against the latest CSOM version for any platform. This means, you cannot be guaranteed that PnP will build against an older CSOM version if new functionality is added.

If you are working with on-prem you should in theory always use the PnP version built against the CSOM version matching you SSOM patch level. Of course, this excludes you from added functionality or potential bugfixes and improvements. That said, if you always make sure to patch every time you need a new version of PnP, you should be better off - but in real life that might be hard.

That said, you can always add your own assembly redirect sections in a .dll/exe.config file, ensuring you load the version you need. Your points are valid, but not necessarily that easy to fix. And if you follow Microsoft versioning you can never deprecate/remove/cleanup anything - especially for SPO which doesn't really have a major release. It's all tiny additions. In my mind, not having to support 3 year life cycles is a good thing - and my guess is that if we change version schema, we would bump the breaking change number quite often - which would not make it easier for devs - they would still need to update to get fixes/functionality and have to rebuild.

**Comment by jensotto** [comment]
I don't want to start a fight on this, but if your theory is correct and you should always use the CSOM version matching on prem SSOM patch level no one could use PnP framework. In practice those version will never match. SP2013 is currently on  April 2015 CU and SP2016 is on RTM. And all add-ins in the office store would need to be rebuilt each month to be guaranteed to work on SPO if what you say is true. I don't see how your theory could be true. Microsoft does not state this anywhere that I have seen.

**Comment by wobba** [comment]
My point being that when a new CSOM is released it has new methods which is then often used in PnP. As long as you only use methods supported by any SP version, the CSOM version don't matter. For SPO it's not an issue, as it's always patched and supports any new method, and nothing old is "ever" removed.

For many cases using PnP SPO posh works just fine against 2013 on-prem - but for many other cases it won't work due to SSOM not matching.

And, versioning will be discussed, your points are all valid - and I would probably patch those environments if possible from an IT pro perspective ;) totally unrelated to this discussion.

**Comment by jensotto** [comment]
Hope my other [comment ](https://github.com/SharePoint/PnP-Sites-Core/pull/1551#issuecomment-368264860) made it clear so I won't repeat too much of it here. I again think we are thinking about different things. As long as OnPrem server is newer than the CSOM PnP framework is built against there should be no problem. This is not what I try to highlight. As long as you only upgrade to a PnP framework version that uses a CSOM version less to or equal to the on prem version you have you should be fine, unless PnP Framework introduces a breaking change on it's own which should result in a major version change.

An no, I'm not talking on my environments. I'm talking about the CSOM version PnP Framework currently are built against. I have added PR #1572 to upgrade the CSOM version. After your comments I see now that I probably should have done this differently than through a PR. Would it had been better to ad it as an issue? The problem I see is that there are so many issues and it seems easier to get attention to it as a PR, especially when I can do the work for you. Also [SP2013 will soon no longer support the SSOM Patch level](https://blogs.technet.microsoft.com/stefan_gossner/2017/12/13/updated-product-servicing-policy-for-sharepoint-2013/) that matches the CSOM version that PnP framework currently is built against. I assume that the CSOM version also then will go out of support.

**Comment by wobba** [comment]
@jansenbe is this something you could look at?

**Comment by jansenbe** [comment]
Hi @jensotto,

We've upgraded CSOM to a more recent version for SP2013/2016. This does not yet solve your issue of the extensibility requiring the correct version, but the approach we use in PS (which is a kind of assembly redirection) should help and can be implemented in the code you've written that calls PnP Sites core. See a sample at https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/ClientSidePages/ConvertToClientSidePage.cs#L150. For now, I'll close this PR, but feel free to open a new issue to discuss this further

**Pull request closed without merging**
