### PR TITLE
Refactored ObjectListInstance

### PR DESCRIPTION
**Pull request by stevebeauge**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    |  yes (code quality improvements)
| New sample?      | no - yes?
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

The `ObjectListInstance` class is a beast.  Sure it does a lot of things, but most of the code is contained into a few methods. Especially the ProvisionObjects method was a very complicated method that was hundred lines long.

This leads to a few issues:

1. the code is hard to read, even if some regions helped to navigate within the code
2. potential contributions to this method may be tricky because of the potential collisions between multiples PR. This risk is lowered when changed occurs on small methods.

That's why I propose this PR. It includes:

* important parts of the ProvisionObjects was extracted as new methods
* UpdateList has been simplified by using a small helper method. this reduced the use of nested ifs to check for different values
* Small improvements : does not return token parser in methods where it was passed as paremeter (as it's a reference type), rely on XElement implicit conversion (casting to string instead of checking for nullity before reading,...)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @stevebeauge - we will try to get this processed asap, since this is a really central file in the engine. In general great to get the main function split as you have done.

**Comment by stevebeauge** [comment]
Merged latest addition

**Comment by stevebeauge** [comment]
Hi @VesaJuvonen,

Do you have any update? This PR concerns a class subject to frequent submission (mines and other contributors). Maintaining branches for PR can be tricky when accumulating commits to merge.

Thanks

**Comment by erwinvanhunen** [comment]
Thanks Steve!

**Pull request merged**
