### PR TITLE
Fix GetPnPProvisioningTemplate/ApplyPnPProvisioningTemplate fails if there is no app catalog site in the tenant

### LINKED ISSUE #1522: Apply-PnPProvisioningTemplate fails on a tenant without App Catalog site
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Expected or Desired Behavior
I have a simple XML defining some custom objects to be applied as template: few custom site fields, one custom content type using these fields, one custom list using this content type.
I have a blank site, and I want to provision these custom objects in my template to my site, using Apply-PnPProvisioningTemplate 

#### Observed Behavior
Getting an error:

> Apply-PnPProvisioningTemplate : {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}}

#### Steps to Reproduce
My tenant doesn't have a App Catalog site collection associated yet. If I create a new App Catalog site for the tenant via Admin center, the error goes and my template is applied correctly.

Still, I don't see any reason of having an explicit dependency on the app catalog, in this case; so I think it's a bug.

Massimo

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        |  yes
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #1522 , PR #1525 

#### What's in this Pull Request?

The issue #1522 is still present. 
To reproduce, create a brand new tenant.
Create a simple site collection or a subsite. I created a classic team site (STS#0)
Run the `Get-PnPProvisioningTemplate` of PnP PowerShell or call the `GetPnPProvisioningTemplate` CSOM Core method to extract the template.
It will fail.
So, have added a try-catch block in the outer section to swallow this error so that template extraction will continue.

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi @gautamdsheth,
Thanks for your contribution. I'll look into this PR in much more detail. However, at first sight, I'm not keen to a _try ... catch_ block that catches and hides any exception. Most likely, I will make some refactoring before merging. Thanks.

**Comment by gautamdsheth** [comment]
Ciao @PaoloPia , agree with you. It was not the correct way to go about this issue. Have modified the `ObjectLifeCycleManagement.cs` file to determine whether tenant app catalog exists or not. Also, undid the `AppManager.cs` file changes.  Let me know your thoughts.

Cheers,
Gautam

**Comment by PaoloPia** [comment]
Hi @gautamdsheth,
It looks great! I will merge it. Thanks!

**Comment by biste5** [comment]
great stuff @gautamdsheth !

**Pull request merged**
