### PR TITLE
Fix RepostPage Set BannerImageUrl

### PR DESCRIPTION
**Pull request by czullu**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | #2149 , #2143 

#### What's in this Pull Request?
The BannerImageUrl has not been set from pageHeader.ImageServerRelativeUrl since a RepostPage Header is read as Default and not Custom.

Did change ClientSidePage.cs ->Save to set BannerImageUrl if layoutType is Repost and Header Default

@jansenbe : Sorry did first just Test if Page not broken &clean checkin now

### CODE REVIEW

**Comment by jansenbe** [comment]
Hey @czullu ,

It feels wrong to set the page header image on a page that does not show this just because we happen to take that image as BannerImageUrl...what's wrong with simply defining the BannerImageUrl field yourselves?

Note that you now can create a RePostPage using the provisioning engine like shown below (it's missing field values for BannerImageUrl and Description)

```XML
<pnp:ClientSidePage PageName="repostClone.aspx" PromoteAsNewsArticle="true" Overwrite="true" Title="Repost clone" Layout="RepostPage">
          <pnp:Header Type="Default" />
          <pnp:FieldValues>
            <pnp:FieldValue Key="_OriginalSourceUrl" Value="https://www.techradar.com/news/windows-10-april-2019-update-release-date-news-and-features" />
            <pnp:FieldValue Key="_OriginalSourceSiteId" Value="00000000-0000-0000-0000-000000000000" />
            <pnp:FieldValue Key="_OriginalSourceWebId" Value="00000000-0000-0000-0000-000000000000" />
            <pnp:FieldValue Key="_OriginalSourceListId" Value="00000000-0000-0000-0000-000000000000" />
            <pnp:FieldValue Key="_OriginalSourceItemId" Value="00000000-0000-0000-0000-000000000000" />
          </pnp:FieldValues>
        </pnp:ClientSidePage>
```

**Comment by czullu** [comment]
Hi Bert

I did run 2 Testcases – first one is a RepostPage to a SP-Page in an other Sites such as a central guidance Page which should appear in any new Site. Second as you did a RepostPage to a external Source.
The Issue I had was, that the Snapshot-Image created when creating the RepostPage based on the Url was missing after provisioning even the the Page and therefore there was no preview on it.

The exact XML-Part for the external Use-Case is as follows:

<pnp:ClientSidePage Overwrite="true" Title="mondaycoffee homepage" ContentTypeID="0x0101009D1CB255DA76424F860D91F20E6C4118002A50BFCFB7614729B56886FADA02339B" PromoteAsNewsArticle="false" PageName="mondaycoffee-homepage.aspx" Layout="RepostPage"><file:///C:/Users/zullu/AppData/Local/Temp/2/7zOCFBEE3B9/9bdfb991-21fb-4974-86c2-ef8bcd0dec0e.xml><pnp:Header Type="Default" ServerRelativeImageUrl="{hosturl}{site}/SiteAssets/SitePages/mondaycoffee-homepage/RepostBanner.png"/><pnp:FieldValues><file:///C:/Users/zullu/AppData/Local/Temp/2/7zOCFBEE3B9/9bdfb991-21fb-4974-86c2-ef8bcd0dec0e.xml><pnp:FieldValue Value="0x0101009D1CB255DA76424F860D91F20E6C4118002A50BFCFB7614729B56886FADA02339B" Key="ContentTypeId"/><pnp:FieldValue Value="Out-of-the-box collaboration solutions for businesses of all sizes and from all industries." Key="Description"/><pnp:FieldValue Value="https://mondaycoffee.com" Key="_OriginalSourceUrl"/><pnp:FieldValue Value="00000000-0000-0000-0000-000000000000" Key="_OriginalSourceSiteId"/><pnp:FieldValue Value="00000000-0000-0000-0000-000000000000" Key="_OriginalSourceWebId"/><pnp:FieldValue Value="00000000-0000-0000-0000-000000000000" Key="_OriginalSourceListId"/><pnp:FieldValue Value="00000000-0000-0000-0000-000000000000" Key="_OriginalSourceItemId"/></pnp:FieldValues></pnp:ClientSidePage>

The fix makes sure that the Preview / SnapShot Image is there and shown to the User after Provisioning.

The Page Header is just set because it must be Empty and the Fallback to SetDefaultPageHeader did put some html into it and then Picture is not shown. In other word – if it is a RePostPage the page.SetDefaultPageHeader() shall not be set – because if it is – the Picture is not shown.

I hope my explanation is ok.

Best regards
Christian

Von: Bert Jansen <notifications@github.com>
Gesendet: Freitag, 26. April 2019 20:39
An: SharePoint/PnP-Sites-Core <PnP-Sites-Core@noreply.github.com>
Cc: Christian Zuellig <czullu@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [SharePoint/PnP-Sites-Core] Fix RepostPage Set BannerImageUrl (#2151)


Hey @czullu<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fczullu&data=02%7C01%7C%7C4af5722ba59e40d6972908d6ca76776b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636919007482895308&sdata=MTyHMrYuved6TK0uKpFFrrTXfbzU9vrzGI8uIP%2Bbeds%3D&reserved=0> ,

It feels wrong to set the page header image on a page that does not show this just because we happen to take that image as BannerImageUrl...what's wrong with simply defining the BannerImageUrl field yourselves?

Note that you now can create a RePostPage using the provisioning engine like shown below (it's missing field values for BannerImageUrl and Description)

<pnp:ClientSidePage PageName="repostClone.aspx" PromoteAsNewsArticle="true" Overwrite="true" Title="Repost clone" Layout="RepostPage">

          <pnp:Header Type="Default" />

          <pnp:FieldValues>

            <pnp:FieldValue Key="_OriginalSourceUrl" Value="https://www.techradar.com/news/windows-10-april-2019-update-release-date-news-and-features" />

            <pnp:FieldValue Key="_OriginalSourceSiteId" Value="00000000-0000-0000-0000-000000000000" />

            <pnp:FieldValue Key="_OriginalSourceWebId" Value="00000000-0000-0000-0000-000000000000" />

            <pnp:FieldValue Key="_OriginalSourceListId" Value="00000000-0000-0000-0000-000000000000" />

            <pnp:FieldValue Key="_OriginalSourceItemId" Value="00000000-0000-0000-0000-000000000000" />

          </pnp:FieldValues>

        </pnp:ClientSidePage>

**Comment by jansenbe** [comment]
Hey @czullu,

When I look at my test page I, for example, see the banner image url set to "https://bertonline.sharepoint.com/sites/ProvisioningTest/SiteAssets/SitePages/Windows-10-May-2019-Update-release-date-news-and-features-TechRadar/RepostBanner.jpg"

A repost page not have a header image, hence it's not correct to use the header image for this, even though the header image will set the banner image when not set upfront. It would be confusing if the API allowed to set a header image while in the UI this is not an option. 

Why can't you simply set the BannerImageUrl field yourself as part of your provisioning? It can be done via code and it can also be done via a provisioning template.

**Comment by czullu** [comment]
Hi Bert
Ok, my explanation was not good.
I can set the BannerImageUrl as FieldValue – this is not the Issue.

The Issue I did try to fix is, that provisioning a RepostPage did set the the Html Values from page.SetDeaultPageHeader() to LayoutWebPartsContent. If LayoutWebPartsContent is not null then the Image set with BannerImageUrl is not shown on the Page.

The Reason I did fix it the way I did was, because I realized that when I load the RepostPage the Header was set as Default. So I did try to find a way where it would work for provisioning and for using ClientSidePage directly.

I other words – you can drop my changes but have to make sure that the LayoutWebPartsContent is null for a RepostPage.

With best regards
Christian



Von: Bert Jansen <notifications@github.com>
Gesendet: Montag, 29. April 2019 04:26
An: SharePoint/PnP-Sites-Core <PnP-Sites-Core@noreply.github.com>
Cc: Christian Zuellig <czullu@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [SharePoint/PnP-Sites-Core] Fix RepostPage Set BannerImageUrl (#2151)


Hey @czullu<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fczullu&data=02%7C01%7C%7C04fa66ad9f8544c8a01f08d6cc200d81%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636920835362803526&sdata=F3Yo1PQBP%2FMebK0eWXuWyHtBovggQHK%2Fn3t%2FyGg8xcM%3D&reserved=0>,

When I look at my test page I, for example, see the banner image url set to "https://bertonline.sharepoint.com/sites/ProvisioningTest/SiteAssets/SitePages/Windows-10-May-2019-Update-release-date-news-and-features-TechRadar/RepostBanner.jpg<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbertonline.sharepoint.com%2Fsites%2FProvisioningTest%2FSiteAssets%2FSitePages%2FWindows-10-May-2019-Update-release-date-news-and-features-TechRadar%2FRepostBanner.jpg&data=02%7C01%7C%7C04fa66ad9f8544c8a01f08d6cc200d81%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636920835362813534&sdata=ppEYP2C5TfIq8MbzHHDOHThLfVEyv0UUjlK4iarcT44%3D&reserved=0>"

A repost page not have a header image, hence it's not correct to use the header image for this, even though the header image will set the banner image when not set upfront. It would be confusing if the API allowed to set a header image while in the UI this is not an option.

Why can't you simply set the BannerImageUrl field yourself as part of your provisioning? It can be done via code and it can also be done via a provisioning template.

**Comment by jansenbe** [comment]
Then I think the logic in the ClientSidePage Save method of the current dev branch should be sufficient (https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs#L757):

```csharp
            // Persist to page field
            if (this.LayoutType == ClientSidePageLayoutType.RepostPage)
            {
                item[ClientSidePage.ContentTypeId] = BuiltInContentTypeId.RepostPage;
                item[ClientSidePage.CanvasField] = "";
                item[ClientSidePage.PageLayoutContentField] = "";
                item.Update();
                this.Context.Web.Context.Load(item);
                this.Context.ExecuteQueryRetry();

                this.pageListItem = item;
                return;
            }
            else
            {
              //...
            }
```

**Comment by czullu** [comment]
Hi Bert
I had no chance to test it, but from what I see it should be OK that way.
I just hope the FieldValue BannerImageUrl from provision XML is not suppressed and loaded to the ClientSidePage model of the Framework to be saved - if I remember correct there is a array of field names used as exclusion list.

I got now rdp access to my dev vm but i"m not sure when I can test run.

Best regards Christian

Freundliche Grüsse
Christian

________________________________

**Comment by jansenbe** [comment]
We're not blocking that and you should be able to also set this field from the provisioning engine. I'll close this PR for now...if you still see issues then let's discuss more.

**Pull request closed without merging**
