### PR TITLE
Fix implementation of the provisioning of dependent lookups fields

### LINKED ISSUE #1133: PnP Provisioning engine fails with dependent lookup
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4875.1000

#### Expected or Desired Behavior
PnP Provisioning engine should handle properly deployments of dependent lookup fields.

#### Observed Behavior
If the provisioning template contains a dependent lookup field, it fails to apply if the target list is itself in the template

The PowerShell console outputs:

````
Apply-PnPProvisioningTemplate : <nativehr>0x80070057</nativehr><nativestack></nativestack>
Au caractère Ligne:1 : 1
+ Apply-PnPProvisioningTemplate -Path $pnpFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
````

In the server logs, I can see this error : `GetLookupListIdAndValidate:Failed to parse Lookup List ID as a GUID.`

Full log in the file [repro.log.txt](https://github.com/SharePoint/PnP-Sites-Core/files/858305/repro.log.txt)

#### Steps to Reproduce

Execute this script (adjust language and paths as required):

```` PowerShell
Add-PSSnapin Microsoft.SharePoint.PowerShell
Import-Module SharePointPnPPowerShell2013 

$url = "http://myserver/sites/13"
$url2 = "http://myserver/sites/14"
$pnpFile = "c:\temp\repro.xml" # xml format for an easier reading 

new-spsite $url -Language 1036 -Template STS#1 -OwnerAlias "$env:USERDOMAIN\$env:USERNAME"

$rootWeb = Get-SPWeb $url

$parentListId = $rootWeb.Lists.Add("Parent", "", [Microsoft.SharePoint.SPListTemplateType]::GenericList)

$childListId = $rootWeb.Lists.Add("Child", "", [Microsoft.SharePoint.SPListTemplateType]::GenericList)


$lookupFieldName = $rootWeb.Fields.AddLookup("Parent lookup", $parentListId, $false)

$lookupField = $rootWeb.Fields.GetFieldByInternalName($lookupFieldName)
$lookupField.LookupField = $rootWeb.Fields[[Microsoft.SharePoint.SPBuiltinFieldId]::ID].InternalName
$lookupField.Update()

# Comments these lines to make the provisioning engine works
$lookupFieldTitleName = $rootWeb.Fields.AddDependentLookup("Parent:Title", $lookupField.Id)
$lookupFieldTitle = $rootWeb.Fields.GetFieldByInternalName($lookupFieldTitleName)
$lookupFieldTitle.LookupField = $rootWeb.Fields[[Microsoft.SharePoint.SPBuiltinFieldId]::Title].InternalName
$lookupFieldTitle.Update()
# / end of lines to comment

$childList = $rootWeb.Lists[$childListId]

$childList.Fields.Add($lookupField)
# Also comment this line to remove the error
$childList.Fields.Add($lookupFieldTitle)

Connect-PnPOnline -Url $url -CurrentCredentials
Get-PnPProvisioningTemplate -Out $pnpFile -Force


new-spsite $url2 -Language 1036 -Template STS#1 -OwnerAlias "$env:USERDOMAIN\$env:USERNAME"

Set-PnPTraceLog -On -LogFile "$pnpFile.log" -Level Debug 

Connect-PnPOnline -Url $url2 -CurrentCredentials
Apply-PnPProvisioningTemplate -Path $pnpFile

````

This small script create a blank site, add a *Parent* list, a *Child* list and a lookup between the two.
Then it exports de site as a PnP template and try to apply it on a new site collection.

If you comments the creation of the dependent lookup, the scripts works. Otherwise, it does not.

### PR DESCRIPTION
**Pull request by stevebeauge**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no 
| Related issues?  | fixes #1133 #1105

#### What's in this Pull Request?

When dealing with lookup and dependent lookup fiels, ordering is important. Lookup fields requires having the target list created, and dependent lookups require havinge the primary lookup available.
I rewrote a bit the three object handlers ObjectField, ObjectContentType and ObjectListInstance to be ran in three sequential stages:

* default stage: provision everything not related to lookup fields
* lookupfield stage to provision everything related to lookupfields
* dependentlookup stage to provision finally the dependent lookups

The order of execution is then (changed in SiteToTemplateConversion):

* ObjectField at stage Default
* ObjectContentType at stage Default
* ObjectListInstance at stage Default
* ObjectField at stage lookupfield 
* ObjectContentType at stage lookupfield 
* ObjectListInstance at stage lookupfield 
* ObjectField at stage dependentlookup 
* ObjectContentType at stage dependentlookup 
* ObjectListInstance at stage dependentlookup 

For each stage, the object providers are filtering the artefact to exclude non relevant fields for the current stage.

That said, I also have to workaround the creation of the dependent lookup itself, because this is the only case (as far as I know) where the standard schema approach can't be used. Only the method AddDependentLookup is working. These method, however, does not allow to specify the ID.... so I faked the system to create a new token, that will match the id in the template and convert it to the actual ID.

These code works with the whole test cases I described in the issue #1133

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Steve, super complex and hard problem to solve. This will be delayed at least beyond November release to ensure that things are working properly. These changes are pretty much on the three most critical object handlers in the engine, so we'll need to be extremely careful with testing.

**Comment by stevebeauge** [comment]
@VesaJuvonen: you are right, these handlers are central pieces of the engine.

I've plan to use in production my changes in the next few weeks. I'll keep updating if anything goes wrong.

**Comment by stevebeauge** [comment]
A few tweaks and optimisations have been pushed.

Here's my complete test case:

````
<?xml version="1.0"?>
<pnp:Provisioning 
  xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.20.1711.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-BB9E1C740D4441938D793E0A2B3357B7">
    <pnp:ProvisioningTemplate ID="TEMPLATE-BB9E1C740D4441938D793E0A2B3357B7" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:SiteFields>
        <Field List="{{listid:TargetList}}" ShowField="Title" Type="Lookup" Description="" DisplayName="TargetLookupField" ID="{49FF941B-4181-4256-B5DA-E0CF61EB189D}" Name="TargetLookupField" WebId="{siteid}" Group="PNP" StaticName="TargetLookupField" SourceID="{8753a1c5-678b-48fa-b2df-daab84b821e8}" />
        <Field DisplayName="Another field" Name="Another field" Type="Text" ID="{A22771F1-334B-4F18-BD32-621F28C73F2D}" Group="PNP" StaticName="Another_x0020_field" SourceID="{8753a1c5-678b-48fa-b2df-daab84b821e8}" />
        <Field Type="Lookup" DisplayName="TargetLookupField:Another field" List="{{listid:TargetList}}" WebId="{siteid}" FieldRef="49ff941b-4181-4256-b5da-e0cf61eb189d" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" Group="PNP" ID="{68142907-bc5b-4cff-8ac0-9bc9b9b42e84}" SourceID="{8753a1c5-678b-48fa-b2df-daab84b821e8}" StaticName="TargetLookupField_x003a_Another_x0020_field" Name="TargetLookupField_x003A_Another_x0020_field" ShowField="Another field" />
      </pnp:SiteFields>
      <pnp:ContentTypes>
        <pnp:ContentType ID="0x01000B97B3EF46799441995A9829F5B6E15E" Name="Content type with Target lookup field" Description="Crée un élément de liste." Group="PNP" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="49ff941b-4181-4256-b5da-e0cf61eb189d" Name="TargetLookupField" />
            <pnp:FieldRef ID="68142907-bc5b-4cff-8ac0-9bc9b9b42e84" Name="TargetLookupField_x003A_Another_x0020_field" />
          </pnp:FieldRefs>
        </pnp:ContentType>
        <pnp:ContentType ID="0x01000C97B3EF46799441995A9829F5B6E15E" Name="Another Content type with Target lookup field" Description="Crée un élément de liste." Group="PNP" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="49ff941b-4181-4256-b5da-e0cf61eb189d" Name="TargetLookupField" />
            <pnp:FieldRef ID="68142907-bc5b-4cff-8ac0-9bc9b9b42e84" Name="TargetLookupField_x003A_Another_x0020_field" />
          </pnp:FieldRefs>
        </pnp:ContentType>
      </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="ListWithContentType" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListWithContentType" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListWithContentType/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListWithContentType/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListWithContentType/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01000B97B3EF46799441995A9829F5B6E15E" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{5376F8DB-18AD-47D2-B315-6602F6D86B8F}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpdeplookups-dest/Lists/ListWithContentType/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="TargetLookupField" />
                <FieldRef Name="TargetLookupField_x003a_Another_" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="49ff941b-4181-4256-b5da-e0cf61eb189d" Name="TargetLookupField" DisplayName="TargetLookupField" />
            <pnp:FieldRef ID="68142907-bc5b-4cff-8ac0-9bc9b9b42e84" Name="TargetLookupField_x003A_Another_" DisplayName="TargetLookupField:Another field" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="AnotherListWithContentType" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/AnotherListWithContentType" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/AnotherListWithContentType/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/AnotherListWithContentType/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/AnotherListWithContentType/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01000C97B3EF46799441995A9829F5B6E15E" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{5376F8DB-18AD-47D2-B315-6602F6D86B8F}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpdeplookups-dest/Lists/AnotherListWithContentType/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="TargetLookupField" />
                <FieldRef Name="TargetLookupField_x003a_Another_" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="49ff941b-4181-4256-b5da-e0cf61eb189d" Name="TargetLookupField" DisplayName="TargetLookupField" />
            <pnp:FieldRef ID="68142907-bc5b-4cff-8ac0-9bc9b9b42e84" Name="TargetLookupField_x003A_Another_" DisplayName="TargetLookupField:Another field" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="ListWithTargetLookup" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListWithTargetLookup" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListWithTargetLookup/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListWithTargetLookup/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListWithTargetLookup/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{39BCEE19-D156-4FC9-A689-00FDD529F452}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpdeplookups-dest/Lists/ListWithTargetLookup/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="TargetLookupField" />
                <FieldRef Name="TargetLookupField_x003a_Another_" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Lookup" DisplayName="TargetLookupField:Another field" List="{listid:TargetList}" WebId="{siteid}" FieldRef="49ff941b-4181-4256-b5da-e0cf61eb189d" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{ed242f1e-5fa8-483b-9f19-f97f6f10d941}" SourceID="{{listid:ListWithTargetLookup}}" StaticName="TargetLookupField_x003a_Another_" Name="TargetLookupField_x003a_Another_" Version="2" ShowField="Another field" />
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="49ff941b-4181-4256-b5da-e0cf61eb189d" Name="TargetLookupField" DisplayName="TargetLookupField" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="TargetList" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/TargetList" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/TargetList/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/TargetList/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/TargetList/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{9A37C0F6-1C4A-4185-9D28-1449401DA349}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpdeplookups-dest/Lists/TargetList/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="Another_x0020_field" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="a22771f1-334b-4f18-bd32-621f28c73f2d" Name="Another_x0020_field" DisplayName="Another field" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
````

**Comment by stevebeauge** [comment]
Removed conflict by merging latest commits from this repo

**Comment by stevebeauge** [comment]
I close this PR because it's too old. Maintaining all changes from the 6 last month is too complicated. 
I start again fixing the issue from the latest dev branch. The #1625 PR replaces this one.

**Pull request closed without merging**
