### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by ivanvagunin**
More unit test for XML fomatters refactoring. Following tests are failing:
- Deserialize regional settings
- Deserialize security
- Serialize list instances
- Serialize property bag entries
- Serialize regional settings
- Serialize template base properties
@PaoloPia could you please review?

### CODE REVIEW

**Comment by ivanvagunin** [comment]
Added fixes for template base properties serialization - now passes

**Comment by ivanvagunin** [comment]
Added fixes for security serialization

**Comment by ivanvagunin** [comment]
Regional settings and property bag entries fixed

**Comment by ivanvagunin** [comment]
Term groups and List instances fixed

**Comment by PaoloPia** [comment]
Hi Ivan,
Thanks for your contribution, this item has been merged into DEV.

**Pull request merged**
