### PR TITLE
Provisioning engine - Support for dynamic loading extensibility provider assemblies

### PR DESCRIPTION
**Pull request by ivanvagunin**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| New sample? | no |
| Related issues? |  |
#### What's in this Pull Request?

Provisioning engine support for for dynamic loading extensibility provider assemblies using file connector. It can be used to load extensibility assemblies from OpenXML package during provisioning, if assemblies were not preloaded to AppDomain. The idea is to have full package (markup+code) that can be provisioned without additional dependencies.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Ivan,
really cool implementation, but this opens up many concerns from security perspective around dynamic assembly usage. Technically absolutely valid, but we feel that this could cause potential issues around securing template files. Concept is absolutely great, but...

**Comment by ivanvagunin** [comment]
Hi Vesa,

Security concerns are totally understandable. Possibility of 3rd party code execution during provision would definitely stop me from using "untrusted" templates. Even if OpenXml template does not contain any custom code, it's hard to find out unless unpacking and checking what is inside.
Also I can see at least 2 issues with current implementation. First it is supposed to be used only with OpenXml but not restricted to, which may result in loading dll files from untrusted location. Second it does incorrect assembly name resolution, which may be exposed to replace trusted assemblies with untrusted ones (I'll try to fix it soon).
Though in real life projects we don't use 3rd party templates nowadays so those risks are really low. As I discussed with Erwin a bit after Adriatics, we (in Knowit) don't use templates for provisioning but rather as development model (provision is only to deploy developed features). That's why it is important for us to have template containing all artifacts including custom code.
However since it can harm in other scenarios I would propose to include it as optional provisioning feature which is disabled by default. So at provision time you can specify some parameter (like -AllowUntrustedCode) to enable dynamic dll loading. Also some kind of warnings or clarification which security threats it may bring could help (especially in case of loading unsigned assemblies).

**Comment by ivanvagunin** [comment]
Hi, I've updated implementation to make assembly loading optional and disabled by default. Also additional security checks like strong name or digital signature can be applied. Well, it does not really verify strong name or signature, it rather checks that one exists.

**Comment by ivanvagunin** [comment]
I guess this one can be closed.

**Pull request closed without merging**
