### PR TITLE
Add List Extensions methods to manage Webhooks subscriptions

### PR DESCRIPTION
**Pull request by ypcode**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no

#### What's in this Pull Request?

List Extension methods to manage List Webhooks subscriptions and all the underlying utilities + related unit tests

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Yannick, 
please remember to sign the CLA at https://cla.microsoft.com. Submission looks good with quick check, but we'll have a closer look on upcoming days. Thx.

**Comment by ypcode** [comment]
Hi @VesaJuvonen, I actually did sign it, and I have a copy the signed document, I was expecting this status to change automatically, I'll redo it ;)

**Comment by jansenbe** [comment]
Thanks @ypcode, you did a great job on the PR. I've merged your PR but also did some additions and refactoring.

**Comment by ypcode** [comment]
You're welcome ;) It's a great honnor to bring my modest contribution to this project ! I plan to do a lot more.

By the way, Can somebody tell me why the CLA is still pending ? I sent an email to the support address but no response yet...

**Pull request merged**
