### PR TITLE
fix List_Pages_UrlName for spanish

### PR DESCRIPTION
**Pull request by kezack**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  |1282

#### What's in this Pull   ##Request?

Change defaultResourceFile in the method GetLocalizedString cmscore to osrvcore for support spanish language.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx zackariya, we'll double check this with language packs.

**Comment by VesaJuvonen** [comment]
Sorry for the wrong click - re-opened.

**Comment by kezack** [comment]
no problem ;)

**Comment by jansenbe** [comment]
Hi @kezack, definitely a valid and good change...merging this one. Thanks for your contribution.

**Pull request merged**
