### PR TITLE
Support switching between Article and Home layout on a modern page

### PR DESCRIPTION
**Pull request by wobba**
| Q               | A
| --------------- | ---
| New feature?    | yes

#### What's in this Pull Request?

Support using both the modern page home page layout as well as the article layout. The home page layout has no header, and is very useful.

### CODE REVIEW

**Comment by wobba** [comment]
Hold on on this. Need to add support so a Home page is created without ooh parts.

**Comment by jansenbe** [comment]
Good stuff Mikael :-)

**Comment by wobba** [comment]
@jansenbe Ok.. added support to keep oob wp's if the layout has any (like the home layout). Option to promote as news as well as set the Title field.

Let me know what you think. The code will allow the change of layout and promoted state - which should be ok I think.

**Comment by wobba** [comment]
@jansenbe Did you get a chance to look at this?

**Comment by jansenbe** [comment]
Hi @wobba,

Yes and no...I did look but did not take action cause I'll process this together with upcoming changes that I'll need to do as we're "improving" the modern pages. So stay tuned :-)

**Comment by wobba** [comment]
Got it.. I'll have to wait before starting powershell dev then to see what it will look like :)

**Comment by jansenbe** [comment]
Hi Mikael, as discussed I've not directly merged your PR but I've taken some of your code and added that as part of bigger refactoring that prepares the PnP engine to support the recently announced modern page capabilities like flexible zones and commenting. Closing this PR now, but we'll credit you  for the input on this one.

**Pull request closed without merging**
