### PR TITLE
High Trust support for on premises

### PR DESCRIPTION
**Pull request by KoenZomers**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | yes
| New sample?      | no
| Related issues?  | N/A

#### What's in this Pull Request?
Added support for high trust on premises authentication through a private certificate

### CODE REVIEW

**Comment by KoenZomers** [comment]
Hold off on merging this request. Just found out it actually reverts back to NTLM and doesn't use the High Trust. Will fix it and submit the fix to this same branch.

**Comment by KoenZomers** [comment]
Fixed now. Go ahead and merge it.

**Comment by KoenZomers** [comment]
Notice that https://github.com/SharePoint/PnP-PowerShell/pull/846 has a depedency on this merge to be done first

**Comment by jansenbe** [comment]
Hi @KoenZomers, thanks for this change. I've evaluated your PR and will merge it.

**Pull request merged**
