### PR TITLE
Extract header image and images linked by quick links webparts

### LINKED ISSUE #2335: -IncludeAllClientSidePages -PersistBrandingFiles does not persist images from header and quick links webpart
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013 

#### Expected or Desired Behavior
This should properly export images linked to by modern pages:

`Get-PnPProvisioningTemplate -Out "template.xml" -IncludeAllClientSidePages -PersistBrandingFiles -Handlers PageContents`

#### Observed Behavior
Above command fails to export certain images. Observed for:

* header images of modern pages
* images used in the quick links web part

#### Steps to Reproduce
* configure a page with header image
* add quick links web part to page
* add link to quick links web part with image chosen from web

### PR DESCRIPTION
**Pull request by heinrich-ulbricht**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #2335 

#### What's in this Pull Request?

Certain images are not exported when using the new -IncludeAllClientSidePages switch in combination with -PersistBrandingFiles. This fixes this at least for some cases. (There may be more).

### CODE REVIEW

**Comment by heinrich-ulbricht** [comment]
@jansenbe 
I modified one RegEx from
`"=[a-fA-F0-9]{8}%2D([a-fA-F0-9]{4}%2D){3}[a-fA-F0-9]{12}"`
to
`"=[a-fA-F0-9]{8}(?:%2D|-)([a-fA-F0-9]{4}(?:%2D|-)){3}[a-fA-F0-9]{12}"`

This now also searches for GUIDs that still have (unencoded) dashes in them and are preceded by an equals sign. I saw this pattern in raw JSON and thought it might be good to detect as well. Hope this is ok.

**Comment by heinrich-ulbricht** [comment]
I also added a handler for an image GUID with curly braces around them and decided against a generic RegEx approach. I rather parse the JSON and look at the spot where I expect this image file GUID.

https://github.com/SharePoint/PnP-Sites-Core/commit/734c889f6bec496fbd331e05c79e5444b2d0de7b#diff-d6fb4a22ad052c8eaee54dcd9e727a37R439

Since everywhere else RegEx is used I wonder if this fits into the general architecture. @jansenbe Is this ok?

**Comment by jansenbe** [comment]
Hey @heinrich-ulbricht ,

Thanks for this contribution. I'll look into this and process it before the September release.

**Comment by jansenbe** [comment]
Merged. I did rewrite the model for header image extraction a bit, can you cross check things still work from your side?

**Comment by jansenbe** [comment]
Just committed some additional changes on this (due to my code refactoring)

**Comment by heinrich-ulbricht** [comment]
@jansenbe Good refactoring. I'll check next time I export modern pages. Currently my approach still is to export and include the whole SiteAssets doclib as well as this makes sure all images are there and it's quite future-proof for new web parts. But exporting only images which are in use is the better approach.

**Pull request merged**
