### PR TITLE
Extensibility handler loading exceptions

### PR DESCRIPTION
**Pull request by jensotto**
| Q               | A
| --------------- | ---
| Bug fix?        | (yes)
| New feature?    | (yes)
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
When applying a provisioning template with an enabled extensibility handler that can not be loaded the provisioning engine will throw an exception. Previously any problems with loading the extensibility handler would silently fail making it difficult for the user to know if the extensibility handler actually performed it's work or not.

With the current versioning scheme it's also required to reference the exact same version in the extensibility handler as the version the provisioning engine uses. This adds to the confusion if the handler has run or not as it's difficult to know if you actually have the same versions of the OfficeDevPnP.Core assembly. Together with my PR #1567 this will be better handled in future releases.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @jensotto, we'll process this asap.

**Comment by wobba** [comment]
Hi @jensotto. As this also affects your version suggestion in #1567 we need to discuss it more before deciding to change the current version schema which is date based.

Have you however tried to add an assembly redirect section to `sharepointpnp.powershell.commands.dll.config` to allow loading of older built extensions which has other version dependencies?

**Comment by jensotto** [comment]
@ wobba this PR should be possible to be implemented regardless of #1567. This PR will surface the loading exceptions that the current versioning scheme creates so that users can get a feedback that the extensibility handler actually never executes.

No I haven't tried the assembly redirect. It's impractical as you would have to do that manually directly in the PowerShell module directory. So it's not something that can be generally used to fix the versioning issue.

**Comment by jensotto** [comment]
@PaoloPia Is it possible to get this fix included soon?

**Comment by PaoloPia** [comment]
Hi @jensotto,
I'm sorry but we need to discuss this PR internally before merging it. Stay tuned and we'll let you know if we will merge it, or if we will solve differently the issue. Thanks.

**Comment by PaoloPia** [comment]
Hi @jensotto,
We had an internal discussion and we decided to merge this PR with some small changes in order to avoid changing the original behavior of the engine, with potential backward compatibility issues. Thanks for your efforts.

**Pull request merged**
