### PR TITLE
Fix implementation of the provisioning of dependent lookups fields

### LINKED ISSUE #1133: PnP Provisioning engine fails with dependent lookup
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4875.1000

#### Expected or Desired Behavior
PnP Provisioning engine should handle properly deployments of dependent lookup fields.

#### Observed Behavior
If the provisioning template contains a dependent lookup field, it fails to apply if the target list is itself in the template

The PowerShell console outputs:

````
Apply-PnPProvisioningTemplate : <nativehr>0x80070057</nativehr><nativestack></nativestack>
Au caractère Ligne:1 : 1
+ Apply-PnPProvisioningTemplate -Path $pnpFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
````

In the server logs, I can see this error : `GetLookupListIdAndValidate:Failed to parse Lookup List ID as a GUID.`

Full log in the file [repro.log.txt](https://github.com/SharePoint/PnP-Sites-Core/files/858305/repro.log.txt)

#### Steps to Reproduce

Execute this script (adjust language and paths as required):

```` PowerShell
Add-PSSnapin Microsoft.SharePoint.PowerShell
Import-Module SharePointPnPPowerShell2013 

$url = "http://myserver/sites/13"
$url2 = "http://myserver/sites/14"
$pnpFile = "c:\temp\repro.xml" # xml format for an easier reading 

new-spsite $url -Language 1036 -Template STS#1 -OwnerAlias "$env:USERDOMAIN\$env:USERNAME"

$rootWeb = Get-SPWeb $url

$parentListId = $rootWeb.Lists.Add("Parent", "", [Microsoft.SharePoint.SPListTemplateType]::GenericList)

$childListId = $rootWeb.Lists.Add("Child", "", [Microsoft.SharePoint.SPListTemplateType]::GenericList)


$lookupFieldName = $rootWeb.Fields.AddLookup("Parent lookup", $parentListId, $false)

$lookupField = $rootWeb.Fields.GetFieldByInternalName($lookupFieldName)
$lookupField.LookupField = $rootWeb.Fields[[Microsoft.SharePoint.SPBuiltinFieldId]::ID].InternalName
$lookupField.Update()

# Comments these lines to make the provisioning engine works
$lookupFieldTitleName = $rootWeb.Fields.AddDependentLookup("Parent:Title", $lookupField.Id)
$lookupFieldTitle = $rootWeb.Fields.GetFieldByInternalName($lookupFieldTitleName)
$lookupFieldTitle.LookupField = $rootWeb.Fields[[Microsoft.SharePoint.SPBuiltinFieldId]::Title].InternalName
$lookupFieldTitle.Update()
# / end of lines to comment

$childList = $rootWeb.Lists[$childListId]

$childList.Fields.Add($lookupField)
# Also comment this line to remove the error
$childList.Fields.Add($lookupFieldTitle)

Connect-PnPOnline -Url $url -CurrentCredentials
Get-PnPProvisioningTemplate -Out $pnpFile -Force


new-spsite $url2 -Language 1036 -Template STS#1 -OwnerAlias "$env:USERDOMAIN\$env:USERNAME"

Set-PnPTraceLog -On -LogFile "$pnpFile.log" -Level Debug 

Connect-PnPOnline -Url $url2 -CurrentCredentials
Apply-PnPProvisioningTemplate -Path $pnpFile

````

This small script create a blank site, add a *Parent* list, a *Child* list and a lookup between the two.
Then it exports de site as a PnP template and try to apply it on a new site collection.

If you comments the creation of the dependent lookup, the scripts works. Otherwise, it does not.

### PR DESCRIPTION
**Pull request by stevebeauge**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no 
| Related issues?  | fixes #1133 #1105. 
| | Replace PR #1415 because PR is 6 month old and is too hard to maintain while merging new releases in the fork. 
| **Other PR required** | #1618 

#### What's in this Pull Request?

When dealing with lookup and dependent lookup fields, ordering is important. Lookup fields requires having the target list created, and dependent lookups require having the primary lookup available.
I rewrote a bit the three object handlers ObjectField, ObjectContentType and ObjectListInstance to be ran in three sequential steps:

* standard list and field step: provision everything not related to lookup fields
* lookupfield step to provision everything related to lookupfields (including dependent lookups)
* remaining list settings step to provision what wasn't yet provisioned regarding lists (views, ...)

The order of execution is then (changed in SiteToTemplateConversion):

* ObjectField at step ListAndStandardFields
* ObjectContentType at step ListAndStandardFields
* ObjectListInstance at step ListAndStandardFields
* ObjectField at step LookupFields
* ObjectContentType at step LookupFields
* ObjectListInstance at step LookupFields
* ObjectListInstance at step ListSettings

For each step , the object providers are filtering the artefact to exclude non relevant fields for the current step .

There's also an "Export" step, related to exporting a template. There's no custom logic in this step, just a label to avoid confusion.
I successfully tested:

* Exporting a template
* importing lookup site fields and dependent lookup site fields
* importing a content type referencing such field
* importing a list bound the content type
* importing a list having the site lookup field referenced
* importing a list having a local lookup field
* importing a list in a subsite referencing the site lookup field
* Importing a list in a subsite having a local lookup field target a list in the subsite

Here are my two xml file for testing (the former is for the root site, the later for the subsite)

Root site template: 

````
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.24.1803.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-C7B2C8D9C7624A1B8EF70E8A2C6DD84D">
    <pnp:ProvisioningTemplate ID="TEMPLATE-C7B2C8D9C7624A1B8EF70E8A2C6DD84D" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:SiteFields>
        <Field List="{{listid:TargetList}}" ShowField="Title" Type="Lookup" Description="" DisplayName="SiteLookupField" ID="{1733FCB6-D6FF-4514-839E-48A512F89D63}" Name="SiteLookupField" WebId="{{siteid}}" Group="PNP" StaticName="SiteLookupField" SourceID="{{siteid}}" />
        <Field DisplayName="SiteFieldA" Name="SiteFieldA" Type="Text" ID="{181F0BDA-C959-4C36-9C15-0C585F7E2F59}" Group="PNP" StaticName="SiteFieldA" SourceID="{f95ae69c-467e-4985-863f-46faf8933b32}" />
        <Field Type="Lookup" DisplayName="SiteLookupField:SiteFieldA" List="{{listid:TargetList}}" WebId="{siteid}" FieldRef="1733fcb6-d6ff-4514-839e-48a512f89d63" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" Group="PNP" ID="{455705f3-a87c-4922-a228-fde76507c0e6}" SourceID="{{siteid}}" StaticName="SiteLookupField_x003a_SiteFieldA" Name="SiteLookupField_x003A_SiteFieldA" ShowField="SiteFieldA" />
        <Field Type="Lookup" DisplayName="SiteLookupField:ListFieldA" List="{{listid:TargetList}}" WebId="{siteid}" FieldRef="1733fcb6-d6ff-4514-839e-48a512f89d63" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" Group="PNP" ID="{4b3673f6-0a6f-43e6-83db-3fdee91be367}" SourceID="{{siteid}}" StaticName="SiteLookupField_x003a_ListFieldA" Name="SiteLookupField_x003A_ListFieldA" ShowField="ListFieldA" />
      </pnp:SiteFields>
      <pnp:ContentTypes>
        <pnp:ContentType ID="0x01003EAA0390AF97BD4B8A67AAC39BF77ECC" Name="Content type with lookup" Description="Crée un élément de liste." Group="PNP" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="1733fcb6-d6ff-4514-839e-48a512f89d63" Name="SiteLookupField" />
            <pnp:FieldRef ID="455705f3-a87c-4922-a228-fde76507c0e6" Name="SiteLookupField_x003A_SiteFieldA" />
            <pnp:FieldRef ID="4b3673f6-0a6f-43e6-83db-3fdee91be367" Name="SiteLookupField_x003A_ListFieldA" />
          </pnp:FieldRefs>
        </pnp:ContentType>
      </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="ListWithContentType" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListWithContentType" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListWithContentType/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListWithContentType/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListWithContentType/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01003EAA0390AF97BD4B8A67AAC39BF77ECC" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{015D3B6B-EDE3-440F-95CE-71025ED03655}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/Lists/ListWithContentType/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="SiteLookupField" />
                <FieldRef Name="SiteLookupField_x003A_ListFieldA" />
                <FieldRef Name="SiteLookupField_x003A_SiteFieldA" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off" />
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="1733fcb6-d6ff-4514-839e-48a512f89d63" Name="SiteLookupField" DisplayName="SiteLookupField" />
            <pnp:FieldRef ID="455705f3-a87c-4922-a228-fde76507c0e6" Name="SiteLookupField_x003A_SiteFieldA" DisplayName="SiteLookupField:SiteFieldA" />
            <pnp:FieldRef ID="4b3673f6-0a6f-43e6-83db-3fdee91be367" Name="SiteLookupField_x003A_ListFieldA" DisplayName="SiteLookupField:ListFieldA" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="ListWithLocalLookup" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListWithLocalLookup" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListWithLocalLookup/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListWithLocalLookup/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListWithLocalLookup/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{69CBFFEC-37AA-4501-8338-317A10EABFB5}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/Lists/ListWithLocalLookup/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="LocalLookupFieldA" />
                <FieldRef Name="LocalLookupFieldA_x003a_ListFiel" />
                <FieldRef Name="LocalLookupFieldA_x003a_SiteFiel" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field List="{listid:TargetList}" ShowField="Title" Type="Lookup" Description="" DisplayName="LocalLookupFieldA" ID="{5cf8dcbb-8f69-4ac1-8a14-1a3e5f1f4fa1}" Name="LocalLookupFieldA" WebId="{{siteid}}" Group="" Version="2" StaticName="LocalLookupFieldA" SourceID="{{listid:ListWithLocalLookup}}" ColName="int1" RowOrdinal="0" />
            <Field Type="Lookup" DisplayName="LocalLookupFieldA:ListFieldA" List="{listid:TargetList}" WebId="{siteid}" FieldRef="5cf8dcbb-8f69-4ac1-8a14-1a3e5f1f4fa1" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{c6e30a27-bfdc-4549-9763-fa17ea5222e3}" SourceID="{{listid:ListWithLocalLookup}}" StaticName="LocalLookupFieldA_x003a_ListFiel" Name="LocalLookupFieldA_x003a_ListFiel" Version="2" ShowField="ListFieldA" />
            <Field Type="Lookup" DisplayName="LocalLookupFieldA:SiteFieldA" List="{listid:TargetList}" WebId="{siteid}" FieldRef="5cf8dcbb-8f69-4ac1-8a14-1a3e5f1f4fa1" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{91f3e757-f6d3-4d74-8005-b836d14b4e51}" SourceID="{{listid:ListWithLocalLookup}}" StaticName="LocalLookupFieldA_x003a_SiteFiel" Name="LocalLookupFieldA_x003a_SiteFiel" Version="2" ShowField="SiteFieldA" />
          </pnp:Fields>
        </pnp:ListInstance>
        <pnp:ListInstance Title="ListWithSiteLookup" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListWithSiteLookup" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListWithSiteLookup/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListWithSiteLookup/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListWithSiteLookup/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{4DEF9735-D09E-4C54-83F0-CE5018541A89}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/Lists/ListWithSiteLookup/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="SiteLookupField" />
                <FieldRef Name="SiteLookupField_x003a_ListFieldA" />
                <FieldRef Name="SiteLookupField_x003a_SiteFieldA" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Lookup" DisplayName="SiteLookupField:ListFieldA" List="{listid:TargetList}" WebId="{siteid}" FieldRef="1733fcb6-d6ff-4514-839e-48a512f89d63" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{73af1cff-b603-4b74-86fa-f74568e86bc5}" SourceID="{{listid:ListWithSiteLookup}}" StaticName="SiteLookupField_x003a_ListFieldA" Name="SiteLookupField_x003a_ListFieldA" Version="2" ShowField="ListFieldA" />
            <Field Type="Lookup" DisplayName="SiteLookupField:SiteFieldA" List="{listid:TargetList}" WebId="{siteid}" FieldRef="1733fcb6-d6ff-4514-839e-48a512f89d63" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{939a71cc-166a-4ed5-818e-96038565ab9d}" SourceID="{{listid:ListWithSiteLookup}}" StaticName="SiteLookupField_x003a_SiteFieldA" Name="SiteLookupField_x003a_SiteFieldA" Version="2" ShowField="SiteFieldA" />
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="1733fcb6-d6ff-4514-839e-48a512f89d63" Name="SiteLookupField" DisplayName="SiteLookupField" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="TargetList" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/TargetList" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/TargetList/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/TargetList/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/TargetList/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{98569F0E-BC25-42A9-85FA-CFBB04AEF90D}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/Lists/TargetList/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="SiteFieldA" />
                <FieldRef Name="ListFieldA" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field DisplayName="ListFieldA" Name="ListFieldA" Type="Text" ID="{14e5a21f-ef69-4903-9e41-e31a5cae3346}" Group="" Version="2" StaticName="ListFieldA" SourceID="{{listid:TargetList}}" ColName="nvarchar4" RowOrdinal="0" />
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="181f0bda-c959-4c36-9c15-0c585f7e2f59" Name="SiteFieldA" DisplayName="SiteFieldA" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
````

Subsite template:
````
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.24.1803.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-951CFB032CA645D5A37C9AF8D495CC86">
    <pnp:ProvisioningTemplate ID="TEMPLATE-951CFB032CA645D5A37C9AF8D495CC86" Version="1" BaseSiteTemplate="STS#0" Scope="Web">
      <pnp:Lists>
        <pnp:ListInstance Title="Documents" Description="" DocumentTemplate="{site}/Documents partages/Forms/template.dotx" OnQuickLaunch="true" TemplateType="101" Url="Documents partages" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" EnableAttachments="false" DefaultDisplayFormUrl="{site}/Documents partages/Forms/DispForm.aspx" DefaultEditFormUrl="{site}/Documents partages/Forms/EditForm.aspx" DefaultNewFormUrl="{site}/Documents partages/Forms/Upload.aspx" ImageUrl="/_layouts/15/images/itdl.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{9D13EC8A-CD16-48B5-A750-7F9F0F9030F2}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les documents" Url="/sites/106/subsite/Documents partages/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="FileLeafRef" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="DocIcon" />
                <FieldRef Name="LinkFilename" />
                <FieldRef Name="Modified" />
                <FieldRef Name="Editor" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
        </pnp:ListInstance>
        <pnp:ListInstance Title="ListInSubsite" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ListInSubsite" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/ListInSubsite/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/ListInSubsite/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/ListInSubsite/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{0D650E33-CBA5-4242-A78F-12A08FCE9B6D}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/subsite/Lists/ListInSubsite/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="SiteLookupField" />
                <FieldRef Name="SiteLookupField_x003A_SiteFieldA" />
                <FieldRef Name="SiteLookupField_x003A_ListFieldA" />
                <FieldRef Name="LocalLookupFieldInSubsite" />
                <FieldRef Name="LocalLookupFieldInSubsite_x003a_" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Lookup" DisplayName="LocalLookupFieldInSubsite" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:SubTargetList}" ShowField="Title" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{e61f21d5-a02a-4ea0-99ef-5e8b7338f38c}" SourceID="{{listid:ListInSubsite}}" StaticName="LocalLookupFieldInSubsite" Name="LocalLookupFieldInSubsite" ColName="int2" RowOrdinal="0" />
            <Field Type="Lookup" DisplayName="LocalLookupFieldInSubsite:LocalFieldInSubsite" List="{listid:SubTargetList}" WebId="{siteid}" ShowField="LocalFieldInSubsite" FieldRef="e61f21d5-a02a-4ea0-99ef-5e8b7338f38c" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{8894bc3e-f198-44df-bacf-ed647917e6e3}" SourceID="{{listid:ListInSubsite}}" StaticName="LocalLookupFieldInSubsite_x003a_" Name="LocalLookupFieldInSubsite_x003a_" Version="1" />
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="1733fcb6-d6ff-4514-839e-48a512f89d63" Name="SiteLookupField" DisplayName="SiteLookupField" />
            <pnp:FieldRef ID="455705f3-a87c-4922-a228-fde76507c0e6" Name="SiteLookupField_x003A_SiteFieldA" DisplayName="SiteLookupField:SiteFieldA" />
            <pnp:FieldRef ID="4b3673f6-0a6f-43e6-83db-3fdee91be367" Name="SiteLookupField_x003A_ListFieldA" DisplayName="SiteLookupField:ListFieldA" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="SubTargetList" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/SubTargetList" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/SubTargetList/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/SubTargetList/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/SubTargetList/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" IsApplicationList="false" ReadSecurity="0" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{567AE247-B9DD-4FDD-A182-F24F67A9F8C9}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/106/subsite/Lists/SubTargetList/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="LocalFieldInSubsite" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Text" DisplayName="LocalFieldInSubsite" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{495578ea-4fa0-497f-b72c-fc7820c690a6}" SourceID="{{listid:SubTargetList}}" StaticName="LocalFieldInSubsite" Name="LocalFieldInSubsite" ColName="nvarchar3" RowOrdinal="0" />
          </pnp:Fields>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
````

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Steve, we'll have a look at this soon.

**Comment by NicolajHedeager** [comment]
Thanks @stevebeauge 

Now I get the reason behiind it.
No worries about the optimization. We have removed it for now. Maybe I can find time to have a look at it myself.

**Comment by okms** [comment]
This change (apart from making priovisioning time 3x slower) causes XSLT listview webparts to _not_ be provisioned if they belong to lists with RemoveExistingViews=true. 

cc: @erwinvanhunen @VesaJuvonen

**Comment by stevebeauge** [comment]
@okms : can you submit an issue with more details ?

**Pull request merged**
