### PR TITLE
BuildTokenCache bug

### PR DESCRIPTION
**Pull request by SchauDK**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | N/A

#### What's in this Pull Request?

BuildTokenCache is storing values in the TokenDictionary with an unescaped key, but checking using a key which is not unescaped.

Furthermore ObjectListInstance.ProcessFieldRefs has become extremely slow as the LINQ is calling ParseString. ParseString is removed as I cannot see that it should be necessary to just get the ID attribute.

### CODE REVIEW

**Comment by wobba** [comment]
I'll include the tokenparser changes in a manual merge with #1968 and some other cleanup. See https://github.com/wobba/PnP-Sites-Core/tree/tokenimprov for now.

And we cannot remove `parseString` for the id, as some templates are using a token as the id.

The refactorings by @stevebeauge which solved an important issue did decrease perf a lot, especially for larger templates - which I managed to speed up again quite a bit with the refactoring of how the token parsing now works.

If you have suggestions to speed up Linq, that be local/global caching, pre-checking etc, I'm all for it.

Do you have benchmarks on how much that one `parseString` impacts a particular template?

**Comment by wobba** [comment]
Manually merged with #1975

**Comment by SchauDK** [comment]
Thanks @wobba 

I've done a benchmark for a template with 16 lists.
The average execution time per iteration is
Without parseString: 13ms
With parseString: 198215ms

So it is REALLY bad.
I'll come up with at suggestion to speed up the LINQ.

**Comment by wobba** [comment]
@SchauDK I totally see why it happens, can you pull down the latest branch and see how much my latest commit helped? Added a guid check to avoid iterating all tokens for a match.

**Comment by SchauDK** [comment]
@wobba It's for sure better.
Avg. execution time is now down to 13946ms.

What do you think about this change to completely remove the performance issue within ProcessFieldRefs?
https://github.com/SchauDK/PnP-Sites-Core/tree/ProcessFieldrefsImprovement

**Comment by wobba** [comment]
@SchauDK ..if you create a PR with that branch I can have a look at getting it in.

**Comment by SchauDK** [comment]
@wobba Created PR. Sorry, haven't had time to add tests.

**Pull request closed without merging**
