### PR TITLE
Fixed deadlock on extracting webhook subscription on lists.

### PR DESCRIPTION
**Pull request by TanmayDharmaraj**
| Q               | A
| --------------- | ---
| Bug fix?       | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | #1343 

#### What's in this Pull Request?
Provisioning template deadlocks when extracting web hook subscriptions for lists via an async API. 
Had to use Task.Run specifically because it is not possible to make the ExtractObjects method async as it would warrant a change in all classes implementing this interface.

### CODE REVIEW

**Comment by TanmayDharmaraj** [comment]
Hi @biste5 
Thanks for the tip. Made the necessary changes.

**Comment by TanmayDharmaraj** [comment]
Hi,
Is there any update on this ? 

Thanks.

**Comment by biste5** [comment]
It'll be likely be merged next week Friday. Normally it happens the first Friday of the month

Massimo

**Comment by jansenbe** [comment]
Just merged this one, did however created a new method GetWebhookSubscriptionsAsync extension method

**Pull request merged**
