### PR TITLE
PageExport of data-sp-htmlproperties to Template and Provisioning to Page fixed

### PR DESCRIPTION
**Pull request by czullu**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
ExtractClientSidePage exports now JSON Encoded the HtmlProperties and HtmlPropertiesData from ClientSideWebPart to JsonControlData of Control so they will be in PnP-Template.xml 

RenderHtmlProperties of ClientSideWebPart gives HtmlPropertiesData if they exist

@jansenbe : Fix HtmlProperties and HtmlPropertiesData on Export & Provision since we had issues with WebParts missing this data after provisioning the Page. To my understanding the data structure in this fields is up to the Programmer so i just encode content with JsonConvert.ToString(HtmlPropertiesData, '"', StringEscapeHandling.EscapeHtml) in order not to break the rest of the JSON Object.

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi @czullu ,

I'm not sure why you need to export these, especially if serverProcessedContent is available? ServerProcessedContent is the JSON representation of HtmlPropertiesData and at save time we translate ServerProcessedContent into the correct HtmlPropertiesData structure. 

Are you trying to fix the case where that there's no ServerProcessedContent data available but there is the HtmlPropertiesData?

**Comment by czullu** [comment]
Hi Bert

Currently I'm on vacation with limited access to the computer.

What I recall, I have the case where the webpart does not show content until I edit the page and save it again after provision page. If I do edit and save the hmtlpropertiesdata is restored. In order to have content shown after provision I had to restore htmlpropertiesdata as well.

I will see that I get access tomorrow and follow up also your other questions.

Best regards
Christian

Freundliche Grüsse
Christian

________________________________

**Comment by jansenbe** [comment]
No rush, enjoy your vacation!

**Comment by jansenbe** [comment]
Hi @czullu ,

I'm closing this PR as I we can't merge it. If that additional data needs to be exported then we need to somehow translate it into serverProcessedContent I think. Would also need a repro of the problem so that we can verify the solution.

**Pull request closed without merging**
