### PR TITLE
Fix for issue #1522

### LINKED ISSUE #1522: Apply-PnPProvisioningTemplate fails on a tenant without App Catalog site
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Expected or Desired Behavior
I have a simple XML defining some custom objects to be applied as template: few custom site fields, one custom content type using these fields, one custom list using this content type.
I have a blank site, and I want to provision these custom objects in my template to my site, using Apply-PnPProvisioningTemplate 

#### Observed Behavior
Getting an error:

> Apply-PnPProvisioningTemplate : {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}}

#### Steps to Reproduce
My tenant doesn't have a App Catalog site collection associated yet. If I create a new App Catalog site for the tenant via Admin center, the error goes and my template is applied correctly.

Still, I don't see any reason of having an explicit dependency on the app catalog, in this case; so I think it's a bug.

Massimo

### PR DESCRIPTION
**Pull request by PaoloPia**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #1522 

#### What's in this Pull Request?

A small fix to a bug referenced in #1522 and related to the TokenParser searching for apps in the AppCatalog.

### CODE REVIEW

**Comment by Didichoune** [comment]
Get-PnPProvisioningTemplate : {"error":{"code":"-1,
Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the
request SP.RequestContext.current/web/tenantappcatalog/."}}}
At line:1 char:9
+ $file = Get-PnPProvisioningTemplate -Out ".\parent.xml" -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

**Comment by Didichoune** [comment]
The issue is not yet REDOLVED !!!!

**Comment by Didichoune** [comment]
RESOLVED

**Comment by Didichoune** [comment]
I would like understand who develop this because let this bug like this. It's not acceptable, I'm sorry !!!

**Comment by Didichoune** [comment]
Wake up guys !!!

**Comment by stevebeauge** [comment]
@Didichoune : please do not forget that this is a community driven project, open source. There's no support, no paid team behind. Only volunteers that offer a bit of their time to contribute to the project. The project is still young and has a lot of ways to improve it. If the rhythm is not fast enough to solve your needs, you are welcome to help by contributing yourself.

**Pull request merged**
