### PR TITLE
Feature/better hidden fields from content types handling

### LINKED ISSUE #1347: PnP Provisionning engine does not handle properly hidden fields in content types
## Category
* [X] Bug
* [ ] Enhancement

## Environment
* [X] Office 365 / SharePoint Online
* [ ] SharePoint 2016
* [X] SharePoint 2013

(didn't tested on 2016, but I guess it's also applicable)

## Expected or Desired Behavior

The PnP provisionning engine should deals with fields hidden in content type properly.

For example, if a field is added to two content types and if the field is made hidden in one of the content types, the field should be visible in the forms only from the content where the field is not hidden.

The field should also remained available in view setup (view field, filter or sort criteria).

These kind of scenarios is common when these fields are populated from external process (workflow or custom solution), and should remain readonly to the users.

## Observed Behavior

Depending of the order the artefact are added to the list, the field may be not working as expected. More precisely, the first artefact that add the field to list will set the hidden attribute of the field forever.

If the list does not yet reference the field, and if you add a content type that hides the field, the field will be added to the list Hidden. There's no way to revert back this attribute (actually, on onprem farm, there are unsupported ways to override the private `CanToggleHidden` property of the field, using reflection... but it's not an applicable solution, especially with O365.).

If the list does not yet reference the field, and if you add a content that does **not** hide the field, the field will be visible. Even you add another content type to the list that hides the field, the field will remain visible in view config and list settings. The visibility in the newform and edit form will respect the content type setup.

If you first add the field to the list, you can add the content types in any order, the field will be properly handled.

## Related issues (guessing it's related)

* #1274
* #871
* #853
* #1002

# Steps to Reproduce

## Create content types

1. Create a field `SomeData` of type text
1. Create a content type `A. CT with hidden field`.
1. Add the field `SomeData` to the content type `A. CT with hidden field`
1. Setup the field in the content type to be hidden
1. Create a content type `B. CT with visible field`.
1. Add the field `SomeData` to the content type `B. CT with visible field`
1. Keep the field as optional in the content type

### Expected behavior of the lists

* the field `SomeDate` is not present in the new form when trying to create an item of type `A. CT with hidden field`
* the field `SomeDate` is present in the new form when trying to create an item of type `B. CT with visible field`
* the field `SomeDate` is available in list settings, view config page (proposed as displayed field, filter or sort criteria)

### Case 1: add `A. CT with hidden field` then `B. CT with visible field`. **Order is important**

1. Create a generic list `1st Case`
1. Enable content type management on this list
1. Add `A. CT with hidden field` content type to the list. Save.
1. Add `B. CT with visible field` content type to the list. Save.
1. Delete `Element` content type from the list. Save.

#### Observed behavior

* [X] **OK** the field `SomeDate` is present in the new form when trying to create an item of type `A. CT with hidden field`
* [ ] **KO** the field `SomeDate` is not present in the new form when trying to create an item of type `B. CT with visible field`
* [ ] **KO** the field `SomeDate` is available in list settings, view config page (proposed as displayed field, filter or sort criteria)

### Case 2: add `B. CT with visible field` then `A. CT with hidden field`. **Order is important**

1. Create a generic list `2nd  Case`
1. Enable content type management on this list
1. Add `B. CT with visible field` content type to the list. Save.
1. Add `A. CT with hidden field` content type to the list. Save.
1. Delete `Element` content type from the list. Save.

#### Observed behavior

* [X] **OK** the field `SomeDate` is present in the new form when trying to create an item of type `A. CT with hidden field`
* [X] **OK** the field `SomeDate` is not present in the new form when trying to create an item of type `B. CT with visible field`
* [X] **OK** the field `SomeDate` is available in list settings, view config page (proposed as displayed field, filter or sort criteria)

### Case 3: add the field `SomeData` then add `A. CT with hidden field` then `B. CT with visible field`. **Order is important**

1. Create a generic list `3rd  Case`
1. Add to the list the site field `SomeData`
1. Enable content type management on this list
1. Add `A. CT with hidden field` content type to the list. Save.
1. Add `B. CT with visible field` content type to the list. Save.
1. Delete `Element` content type from the list. Save.

#### Observed behavior

* [X] **OK** the field `SomeDate` is present in the new form when trying to create an item of type `A. CT with hidden field`
* [X] **OK** the field `SomeDate` is not present in the new form when trying to create an item of type `B. CT with visible field`
* [X] **OK** the field `SomeDate` is available in list settings, view config page (proposed as displayed field, filter or sort criteria)

# Impact on the PnP Provisioning engine

As we have observed, from the order in which elements are added to a list depends the actual behavior of the fields in the list.

However, the PnP Provisioning engine has no clue in which order the elements have to be added to the list. This may leads to a difference beetween the source site and the target site. Even worse, this can leads to blocking errors because the `Hidden` attribute can't be set to false later, when the engine try to update the list's field.

## Repro template

The previous exposed cases leads to this template using `Get-PnPProvisioningTemplate -Handlers Fields,ContentTypes,Lists -out c:\temp\pnpcthiddenfields.xml` command (removed other non important lists):

````
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.19.1710.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-AF7AA091F6D74737B5E6A419A2C183CC">
    <pnp:ProvisioningTemplate ID="TEMPLATE-AF7AA091F6D74737B5E6A419A2C183CC" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:SiteFields>
        <Field Type="Text" DisplayName="SomeData" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" Group="Debug" ID="{801a9d3e-2afd-4ff2-900b-22a3f6e2c103}" SourceID="{1c60f97e-9ce0-4669-b0e4-468217198a5b}" StaticName="SomeData" Name="SomeData">
        </Field>
      </pnp:SiteFields>
      <pnp:ContentTypes>
        <pnp:ContentType ID="0x010026D1CC81F4DF694C89BE46D339AE18B8" Name="B. CT With visible field" Description="" Group="Debug" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="801a9d3e-2afd-4ff2-900b-22a3f6e2c103" Name="SomeData" />
          </pnp:FieldRefs>
        </pnp:ContentType>
        <pnp:ContentType ID="0x01005BADD9555ED9024EA6EE08216A89A536" Name="A. CT With Hidden field" Description="" Group="Debug" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="801a9d3e-2afd-4ff2-900b-22a3f6e2c103" Name="SomeData" Hidden="true" />
          </pnp:FieldRefs>
        </pnp:ContentType>
      </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="1st Case" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/1st Case" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/1st Case/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/1st Case/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/1st Case/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01005BADD9555ED9024EA6EE08216A89A536" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
            <pnp:ContentTypeBinding ContentTypeID="0x010026D1CC81F4DF694C89BE46D339AE18B8" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{3141183C-1CAD-431A-84F8-DE45DD6D6CBC}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpcthiddenfields/Lists/1st Case/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
        </pnp:ListInstance>
        <pnp:ListInstance Title="2nd Case" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/2nd Case" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/2nd Case/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/2nd Case/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/2nd Case/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010026D1CC81F4DF694C89BE46D339AE18B8" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
            <pnp:ContentTypeBinding ContentTypeID="0x01005BADD9555ED9024EA6EE08216A89A536" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{6725F26B-3E09-4AE7-9CEB-B7CBEDB5A0C1}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpcthiddenfields/Lists/2nd Case/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="801a9d3e-2afd-4ff2-900b-22a3f6e2c103" Name="SomeData" DisplayName="SomeData" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
        <pnp:ListInstance Title="3rd case" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/3rd case" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/3rd case/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/3rd case/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/3rd case/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01005BADD9555ED9024EA6EE08216A89A536" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
            <pnp:ContentTypeBinding ContentTypeID="0x010026D1CC81F4DF694C89BE46D339AE18B8" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{FB922BD1-6D85-4369-BD35-276DC46A2E5A}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpcthiddenfields/Lists/3rd case/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="SomeData" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="801a9d3e-2afd-4ff2-900b-22a3f6e2c103" Name="SomeData" DisplayName="SomeData" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
````

Trying to apply this templates using `Apply-PnPProvisioningTemplate -Path C:\temp\pnpcthiddenfields.xml` leads to this error:

> Cannot change Hidden attribute for this field 

# Conclusions

From my opininion, this is clearly a SharePoint bug, not specific to the PnP Provisionning engine.
However, this leads to weird issues with the engine.

Unfortunately, we can't rely on `ShowInEditForm` or `ShowInNewForm` attributes of `FieldRef` elements, because these attributes seems to be avaialable only on server side model.

Regarding the 3 cases, I can imagine some possible workarounds directly in the PnP provisionning engine:

* provision all content types without adding the hidden attribute flag on field references, then provision the lists, and do a 2nd pass on content types to apply the hidden attribute.
* before provisioning `ContentTypeBindings` in the lists, add all fields referenced in the content type to the list.

### PR DESCRIPTION
**Pull request by stevebeauge**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    |  yes (not sure if it's actually a bugfix or a new feature... probably a bit of both)
| New sample?      | no 
| Related issues?  | fixes #1347

#### What's in this Pull Request?

I've a implemented a workaround to the issue #1347 .

When adding a content type to a list, all fields hidden in the content type are firstly added to the list.
This ensure the field will be visible in view settings, etc.

### CODE REVIEW

**Comment by biste5** [comment]
Hi @stevebeauge ,

if I try this implementation with my test case from #1002 , I don't get the exception, but also not the correct end result.

My field should be Hidden in CT, and Optional/Required in the list (this is how is exported), but as result it is still Hidden in the CT association with my list

Massimo

**Comment by stevebeauge** [comment]
@biste5 : not sure to understand. You said "My field should be hidden in CT" and "is still hidden in the CT", which is the same.

Can you clarify ?

**Comment by biste5** [comment]
Hi @stevebeauge ,

Site (collection) Content Type
_MyCT_

Referencing a Site Field
_TestCol_
_TestCol_ is included as **Hidden** in _MyCT_

Custom List
_MyList_
associating _MyCT_

In the association of _MyCT_ in _MyList_ , _TestCol_ is specified as **Optional** instead of **Hidden**

My results after applying a template from #1002 using your code
_TestCol_ in _MyCT_ associaction of _MyList_ is still **Hidden**

**Comment by VesaJuvonen** [comment]
thx @stevebeauge, lot of work done on this one, thanks for that. There's a small merge conflict, which should be though ok. We'll have a look on this soon. Sorry for the small delay.

**Comment by PaoloPia** [comment]
Hi @stevebeauge,
We investigated the issue (#1347) and the code of this PR. Unfortunately, we cannot merge it because it is not backward-compatible (you add a params argument to a public static method). Moreover, based on the comment on issue #1347 we think that we should not fix a bug of SharePoint here. Nevertheless, as already stated in the other issue we are now investigating the PnP bug. I will close this item. Thanks for your cooperation.

**Pull request closed without merging**
