### PR TITLE
added higher async methods for branding extensions

### PR DESCRIPTION
**Pull request by baywet**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | continuation of the effort started in !1559

#### What's in this Pull Request?
I wanted to get early feedback before doing everything @jansenbe @SharePointRadi 
Basically the goal is to provide higher level async methods so concurrency can be managed consistently from end to end.
I did a few things:
- reviewed the approach providing executeretryasync so we don't have to do conditional build all the way up and it'll be easy to provide that for on prem the day on prem CSOM has an async execute query as well.
- provided higher level async methods in branding extensions and switched things so they own the logic.
- wrapped call in the sync methods to provide backward compatibility

#### Guidance
We can either merge that now and author subsequent PR's if you think that's going to be easier or I can keep pushing changes to this one if you give me a go on the approach.
Happy to discuss about it :)

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks @baywet. Getting more async methods is something we clearly need, especially now that we've a .Net Standard 2.0 version of the library that can be used in for example mobile development. Today I did a structural change (https://github.com/SharePoint/PnP-Sites-Core/commit/5dc3e51ebb66c4c55f6f059a2dae0de03a9891ed) for all async methods, which would be something to apply to all methods if it receives positive test feedback from community (to avoid deadlocks). We'll internally discuss about the best approach to move this forward and will let you know asap.

**Comment by baywet** [comment]
Thanks for getting back to me this quick.
Looked at the commit it makes sense. 
I still believe we should avoid conditional build for the ExecuteQueryRetryAsync. Provide it to everybody even if it's not doing async yet because CSOM on prem doesn't have the method.
It'll give people time to remap their code and benefit the performance improvement when we ship an update

**Comment by baywet** [comment]
Hi @jansenbe what was the outcome of the tests you ran for async support? how can we move forward?

**Comment by baywet** [comment]
Refering thed deadlocks and async issues as discussed on the call.
https://github.com/SharePoint/PnP-Sites-Core/issues/1617
https://github.com/SharePoint/PnP-Sites-Core/issues/1537
https://github.com/SharePoint/PnP-Sites-Core/issues/1117
Let me know if I missed anything @jansenbe

**Comment by jansenbe** [comment]
Hi Vincent,

As discussed during the community call thanks for this PR. The current async calls have been tested and the model is working fine so far, hence I would like to ask you to adjust this PR (or create a new one) based upon this model:
- Add `await new SynchronizationContextRemover();` in each publicly called async method, before actual method logic but after argument validation
- Use `Task.Run(() => AddAsync(file, filename, overwrite)).GetAwaiter().GetResult();` model for calling the async method in a synchronous way
- Don't update the ExecuteQueryRetry methods 

See https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/ALM/AppManager.cs for more details on the approach.

**Comment by baywet** [comment]
Hey @jansenbe Thanks for the follow up!
The only difficulty with the current implementation in ClientContextExtensions is that is doesn't provide a ExecuteQueryRetryAsyncMethod, forcing conditional compilation all the way up.
That's going to add a lot of complexity and overhead. I'm going to propose a solution based on your implementation and let me know what you think.

**Comment by baywet** [comment]
there https://github.com/SharePoint/PnP-Sites-Core/pull/1653/commits/7d1ab10f102e4068e4f1a5f4cfdd0ee634715895

**Comment by baywet** [comment]
Alright I aligned the ExternalSharingExtensions, let me know if that matches what you expected. If yes, I'll update the Branding Extensions and we should be ready to merge this PR :)

**Comment by jansenbe** [comment]
Hi Vincent, 

I manually merged the ExternalSharingExtensions.cs file and credited you for the work via the changelog. Looks really good, only minor change I did is instead of using **Base(method)** as the name of the private async method with the core logic I renamed these to be like **(method)Implementation** which is more aligned to how we named things across pnp sites core. Will close this PR for now, would recommend submitting future changes (e.g. async branding extensions) as one PR per extensions file. 

Thanks for the good contribution!

**Comment by baywet** [comment]
Thanks @jansenbe ! I will open other pull requests. hopefully now that things are sorted out it should help streamline other contributions.

**Pull request closed without merging**
