### PR TITLE
Null handling for bing map control property

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        |  yes
| New feature?    | no
| New sample?      | no

#### What's in this Pull Request?

PnP Provisioning template throws error when template has bing map or people webpart because they dont have control property.

So, have added null handling to fix this bug.

Issue - 

1) Create a modern page

2) Add highlighted content webpart, bing map and people webpart in that order

3) Extract the site's template using the Get-ProvisioningTemplate method of CSOM C#

4) Apply the template.

5) It throws value should not be null error.

Fix:

Have added a fix to handle null value of control properties.

### CODE REVIEW

**Comment by jansenbe** [comment]
This should not be needed with the upcoming changes (already in Dev). Checkout the SIG recording from November 30th https://t.co/j4azWO7qp6 to see quicklinks and bingmap being used on a page.

**Comment by gautamdsheth** [comment]
Hey @jansenbe , i tried with latest pnp version `2.22.1801` and still it causes an issue.

Error is as below at [this](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs#L126) line when i try to provision the page.

`Value cannot be null`

**Comment by jansenbe** [comment]
Can you share your provisioning template so I can have a look? Ideally isolate the issue to template having just the page with the failing bing map web part

**Comment by gautamdsheth** [comment]
hey, please find attached the xml as well as the error.

error

[Location.xml.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1621841/Location.xml.txt)

**Comment by jansenbe** [comment]
Just tried and used your XML...but no error and a functional page as result:
image

**Comment by jansenbe** [comment]
Tried using dev branch, provisioning into a modern team site. What type of site are you provisioning into?

Here's the code I used
```C#
            using (var clientContext = TestCommon.CreateClientContext("https://bertonline.sharepoint.com/sites/bert1"))
            {
                ProvisioningTemplateApplyingInformation ptai = new ProvisioningTemplateApplyingInformation()
                {
                    HandlersToProcess = Handlers.PageContents,
                    ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                    {
                        // Only to output progress for console UI
                        Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                    }
                };

                XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp", "");
                ProvisioningTemplate sourceTemplate = provider.GetTemplate("BingMap.xml");

                // Execute actual extraction of the tepmplate
                clientContext.Web.ApplyProvisioningTemplate(sourceTemplate);
            }
```

**Comment by gautamdsheth** [comment]
Hey @jansenbe , please close this PR. Have checked it multiple times and was unable to reproduce the error.

**Pull request closed without merging**
