### PR TITLE
Support sub nodes from Top Nav in RWD mode and other improvements

### PR DESCRIPTION
**Pull request by Laul0**
|  Q              | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| New sample?     | no
| Related issues? | Fixes SharePoint/PnP-Tools/issues/94

#### What's in this Pull Request?
Performs some change to supports subsites node from the Top Navigation into the responsive mode.

##### JavaScript
* Get links and add button when sub nodes are available (with this solution, the user keep the link available and for expand the nodes, he have to click on the button)
* Add an event Listener onto the button at the click event to toggle the parent css class

##### CSS
* Hide or show sub nodes in accordance with the parent class attribute

> Note: this PR was tested on SharePoint 2013/2016 On-Premise and SharePoint Online.

#### Use Case
| Environment | Tested |
|--------------|-------|
| SharePoint 2013 | yes |
| SharePoint 2016 | yes |
| SharePoint Online | yes |

#### Guidance
1. If you have already deployed PnP Responsive UI, you can replace the JS and CSS files, otherwise, follow the guidance at https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.UI.Responsive and replace the files of this PR
2. Create Sub Site that inherit the top navigation
3. For each sub sites, into the navigation settings, check the checkbox "Show subsites"

<a name="overview"></a>
##### Desktop
sp-pnp-responsive-ui_topnav_desktop

##### Tablet
|  Collapse              | Expand
| --------------- | ---
| pr-pnpresponsiveui-tabletmode_collapse | pr-pnpresponsiveui-tabletmode_expand

##### Smartphone
|  Collapse              | Expand
| --------------- | ---
| pr-pnpresponsiveui-smartphonemode_collapse | pr-pnpresponsiveui-smartphonemode_expand

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks @Laul0 for this PR, this is a nice addition. We'll be looking into this

**Comment by Laul0** [comment]
Hi @PaoloPia,
I have a question for you about this MR. I found an improvement to apply to the CSS file, so what I have to do for that you can take this in consideration ?
I have to create a new MR ? Just in comment in this one ? otherwise ?
This improvement consists to support multiple sub menus (the case when you enable the inheritance with sub sites into the top navigation). Thanks by advance

**Comment by PaoloPia** [comment]
Hi,
you can simply add your changes to the MASTER branch of your fork and we will see them in this PR.

**Comment by Laul0** [comment]
Hi @PaoloPia, thx for your answer. I did it and in the same way, I updated my PR comment in accordance with the enhancement.

**Comment by Laul0** [comment]
In addition to the changes, I updated the PR comment : 
* Change screenshots in accordance with the accessibility improvement
* Update SharePoint 2016 tested to Yes

**Comment by PaoloPia** [comment]
Hi Laul0,
I'm testing your changes right now in SP2013 and SP2016. The Responsive UI still works, but I cannot reproduce the UI that you reference in your text (I'm talking about multi-level hierarchical menu items for sub-sites). I don't see the additional hamburger menu and I just see the out of the box UI. Can you give me more depth guidance about how to reproduce the capability? Thanks.

**Comment by PaoloPia** [comment]
Hi @Laul0,
Thanks for the updated code, but I still don't see the additional hamburger menu and I just see the out of the box UI. Can you give me more info about this fix? Thanks.

**Comment by Laul0** [comment]
Hi @PaoloPia,

I used this PR for all of my SharePoint teamsites... And the code seems work. I'll try this version on a other server to be sure and I'll keep you in touch quickly.

**Comment by Laul0** [comment]
Hi @PaoloPia, I'd just tested this version of PnPResponsive on an other server and this version works.

Question : In accordance with your feedback, you can see the box UI to collapse or expend sub nodes... That meen you have the good version of the JS script but you can't see the hamburger... The hamburger is generated with the CSS, so I meen there're two options :
1. The CSS is not up-to-date
2. Cache file
Is it possible that one of this options is the reason of your problem ?

**Comment by PaoloPia** [comment]
Hi @Laul0 ,
When I tested it I used Chrome + F12 with caching disabled. Thus, it shouldn't be the case. What I can try to do is to reload (one more time) the demo in my environment ... I'll let you know ...

**Comment by Laul0** [comment]
Hi @PaoloPia, I send you a mail (paolo@pialorsi.com) to test together on a SharePoint Online environment.
I used this version of JS ans CSS

**Comment by Laul0** [comment]
I close this issue because I'm working on a new major version ;)

This new version will take a lot of existing issues and several improvements.

**Pull request closed without merging**
