### PR TITLE
Feature: webrequest factory

### PR DESCRIPTION
**Pull request by stevebeauge**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | yes
| New sample?      | no 
| Related issues?  | 

#### What's in this Pull Request?

This PR contains a Web Request factory. Its goal is to facilitate creating web requests using client context credentials, and to have the logic in a single place.
It also contains a new class SharePointWebClient, which derivates from System.Net.WebClient.

A few usage of HttpWebRequest in the code has been updated.

The goal is to open a door to add new methods working with raw Http requests, where CSOM does not offer direct API (accessing owssvr.dll related messages, getting file property bag, ...).

This has been tested both with SP 2013 and SP 365.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @stevebeauge, we'll process this asap.

**Comment by stevebeauge** [comment]
I've merged all commits (mostly commits to keep up to date the fork) to simplify the PR

**Comment by jansenbe** [comment]
Hi Steve,

Thanks for your contribution.  We're not going to merge this PR as the type of web requests you're trying to optimize are more exceptionally used. You could perfectly include this webrequestfactory code in your solutions and use it.

**Comment by stevebeauge** [comment]
I use this class, for exemple, to wrap frontpage rpc calls that provides some use case not available in csom (get/set property bag of files or creating webpart pages).
Anyway I understand your position and I'll include the class within custom extensibility providers.

Thx

**Pull request closed without merging**
