### PR TITLE
Creating publishing pages with the provisioning framework

### PR DESCRIPTION
**Pull request by SPParseError**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?

Adding the ability to provision publishing pages with the provisioning framework. Added a new schema (2016/12) for this as it seems to be the practice, and did some other choices like added PublishingPages node in Publishing, and not at root like Pages. I imagine you may want to discuss those choices.

I will update the ProvisioningSchema repository with a new sample if this pull request is accepted. I 

I attached my sample XML (dependencies like files are not included to make it easier to look at)
[ProvisioningTemplate.txt](https://github.com/SharePoint/PnP-Sites-Core/files/614402/ProvisioningTemplate.txt)

### CODE REVIEW

**Comment by SPParseError** [comment]
I forgot to mention that part of my code comes from the sample PnP/Samples/Provisioning.Extensibility.

**Comment by SPParseError** [comment]
My company has accepcted to let the whole team participate on the project, and i moved the repository from a personal respository to an organization one. Is it possible to sign CLA again to specify that my company is involved ?

**Comment by PaoloPia** [comment]
Hi Stéphane,
Thanks for your contribution. Unfortunately we cannot accept it "as is", because the process requires first of all to update the XSD in the main schema repository (https://github.com/SharePoint/PnP-Provisioning-Schema/). We usually release a new schema version once every 4/6 months and we released the last one in May 2016. After the schema definition and approval, we update the engine accordingly and we provide any new functionality based on the new schema elements.

Aside from that, the source code you submitted has some conflicts resolutions that need to be fixed, too. Like for example here (https://github.com/SharePoint/PnP-Sites-Core/pull/861/files#diff-72de89d8eb7e6d5d2922982e34a3dee9R3) and here (https://github.com/SharePoint/PnP-Sites-Core/pull/861/files#diff-72de89d8eb7e6d5d2922982e34a3dee9R94).

Could you please fix them? We will keep this PR open, waiting for the schema to be ready, and then we will evaluate and process it. Thanks again.

**Comment by bartdonninger** [comment]
Hello @SPParseError ,

Great contribution. I'd also like to see this feature in the schema and engine in the upcomming months.

**Comment by SPParseError** [comment]
Ok, i will do the merges soon.

@bartdonninger thanks !

**Comment by SPParseError** [comment]
@PaoloPia to check if i understood, i have to : 
1. Do a pull request on PnP-Provisioning-Schema
2. Merge conflicts on this pull request

**Comment by SPParseError** [comment]
Pull request created on the main schema repository https://github.com/SharePoint/PnP-Provisioning-Schema/pull/157. I will now resove conflicts.

**Comment by SPParseError** [comment]
Conflicts resolved, let me know if i need to do anything else.

**Comment by PaoloPia** [comment]
Hi Stéphane,
accordingly to what I wrote here (https://github.com/SharePoint/PnP-Provisioning-Schema/pull/157) could you please first update the new 201801 schema in the PnP-Provisioning-Schema repository, and afterwards submit a PR here in the PnP-Sites-Core repo, as soon as the new schema will be available in the engine? In the mean time, I will close this PR. Thanks.

**Pull request closed without merging**
