### PR TITLE
Workaround #1236: calucated fields & language issue workaround

### LINKED ISSUE #1236: Calculated colums in site with language other than EN (NL in my case) are not provisioned correctly.
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Calculated colums in site with language other than EN (NL in my case) are not provisioned correctly.

#### Observed Behavior
When template is applied the following error is shown: 

De formule bevat een syntaxisfout of wordt niet ondersteund. a.k.a. The formula has a syntax error.

When examining the PnP template the schema of the field is as follows:

```
<Field Type="Calculated" DisplayName="{res:Field_EmMonth_DisplayName}" Description="{res:Field_EmMonth_Description}" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1043" ResultType="Text" Group=".IMaeS - OPM" ID="{5fabdccc-5a3d-42f0-9686-b9ae60de9b6a}" SourceID="{a0106bfb-dbf9-46f5-9846-ad0d7c607197}" StaticName="imaesEmDateMonth" Name="imaesEmDateMonth" Required="FALSE" AllowDeletion="TRUE" CustomFormatter="" ReadOnly="TRUE">
          <Formula>=TEKST(MAAND(EmDate);0)</Formula>
        </Field>
```

So the formula text is in Dutch. When translating the formula into English format the template application works, but it's hard to maintain like this.

`<Formula>=TEXT(MONTH(EmDate),0)</Formula>`

#### Steps to Reproduce
Connect to site using Connect-PnPOnline
Export site collection template using Get-PnPProvisioningTemplate -Out D:\template.pnp -Handlers Fields
Apply template to new site collection using Apply-PnPProvisioningTemplate -Path D:\template.pnp -Handlers Fields

Template is below:

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.16.1706.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-CAD6048B31B54A6BB2668586EBAF4814">
    <pnp:ProvisioningTemplate ID="TEMPLATE-CAD6048B31B54A6BB2668586EBAF4814" Version="1" BaseSiteTemplate="STS#0">
      <pnp:SiteFields>
        <Field Type="DateTime" DisplayName="EmDate" Description="Email Datum (standaard email Eigenschap OPM)" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" Group="OPM" FriendlyDisplayFormat="Disabled" ID="{92e369dd-5ee1-4dd2-8bd5-1742f779eeff}" SourceID="{a0106bfb-dbf9-46f5-9846-ad0d7c607197}" StaticName="EmDate" Name="EmDate" CustomFormatter="" CalType="0">
        </Field>
        <Field Type="Calculated" DisplayName="EmMonth" Description="Maand van email datum (EmDate)" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1043" ResultType="Text" Group="OPM" ID="{5fabdccc-5a3d-42f0-9686-b9ae60de9b6a}" SourceID="{a0106bfb-dbf9-46f5-9846-ad0d7c607197}" StaticName="imaesEmDateMonth" Name="EmDateMonth" Required="FALSE" AllowDeletion="TRUE" CustomFormatter="" ReadOnly="TRUE">
          <Formula>=TEXT(MONTH(EmDate),0)</Formula>
        </Field>
      </pnp:SiteFields>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

### PR DESCRIPTION
**Pull request by KEMiCZA**
| Q               | A
| --------------- | ---
| Bug fix?        | yes / workaround
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #1236 

#### What's in this Pull Request?
When creating a new calculated sitefield the formula language is expected to be 1033/English. When updating a calculated sitefield the formula language is expected to be in the language of the web (i.e. Dutch1043).

See #1236 for more information.

### CODE REVIEW

**Comment by SchauDK** [comment]
Hi @KEMiCZA 
This workaround doesn't work for me.
It always (both create and update) expects the formula in English. It doesn't matter if the Web is English or non-English.

Also, you're checking if the exception message contains 'syntax', however if the sitecollection is in eg. Danish the message contains 'syntaks'.

Does this still work for you?

**Comment by KEMiCZA** [comment]
@SchauDK hi, for the client I implemented this it worked fine. I don't have the details anymore sadly, so I can't test this anymore. To be honest I'm not totally satisfied with the workaround I provided, because of how I dealt with handling the exception, like you pointed out (checking if the message contains "syntax"). Also this was a fix for an onprem 2016 SharePoint.

Can you check what the language is for the fieldXml variable, when debugging?

**Comment by SchauDK** [comment]
In my case the formula language is Danish, because the template is exported from a Danish solution.

**Comment by jansenbe** [comment]
Closing this PR due to merged fix from @SchauDK (#1970)

**Pull request closed without merging**
