### PR TITLE
Proposal to Fix issue #796

### LINKED ISSUE #796: Handle checked-out files when applying a Provisioning Template
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
  #### Category

[ ] Bug
[X] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Applying a provisioning template overwriting checked out files causes an exception to be thrown. It would be nice to be able to handle this somehow and prevent ApplyProvisioningTemplate to break and skip applying other parts of the template.
#### Observed Behavior

Applying a provisioning template overwriting checked out files causes an exception to be thrown.
#### Steps to Reproduce

Apply a ProvisioningTemplate with Files targeting libraries requiring checking out files. Make sure one of the files is checked out (by a different user).

### PR DESCRIPTION
**Pull request by luismanez**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| Related issues?  | fixes #796

#### What's in this Pull Request?

This PR includes a Proposal to fix issue #796 
What I'm doing is to catch the ServerException in the UploadFile method, and check the Error Code to just ignore the File if the error is "The file is already checked out". Otherwise, if follows the original logic.

### CODE REVIEW

**Comment by luismanez** [comment]
Hi @VesaJuvonen, any idea why this PR hasn´t been included in August release?
Thanks.

**Comment by VesaJuvonen** [comment]
Delay is just due resource challenges - lot of the core team members had summer vacations during July, so we simply did not have time to process the PRs in the typical schedule. We'll catch up on the PRs during upcoming weeks for getting back on top of things. 

So - the reason for the delay was nothing more than people prioritizing their family on the PR processing... We'll get these moving again. :-)

**Comment by luismanez** [comment]
Thought it later, sorry :)
Thanks for the reply.

**Comment by VesaJuvonen** [comment]
thx Luis for this, looks solid. We'll get this processed soon.

**Comment by PaoloPia** [comment]
Hi Luis,
the implementation is ok. I've just merged it. Thanks.

**Pull request merged**
