### PR TITLE
add SynchronizationContextRemover to ExecuteQueryImplementation since…

### LINKED ISSUE #1617: Deadlocks everywhere in PnP Core!!
#### Category
[X] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
PnP Core methods should work no matter if they are called from an MVC or Console or whatever application...

#### Observed Behavior
Many of the newer methods in PnP Core library do not work when using them from an application that has an UI Thread. So putting it the other way, it only works from a console application and that includes the unit tests....
Newer methods in PnP Core that use the Rest API (/_api/XXX) instead of csom are using PnPHttpProvider or a different HttpClient and make async requests using await httpClient.SendAsync(...
But higher up the stack, those are often beeing called within a Task.Run(() => ....
This can lead to deadlocks when using PnP Core with applications that have an UI thread.
You can read more about this here for example: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

#### Steps to Reproduce
Call the new AvailbleClientSideComponents() method from an MVC Application for example. Try to make multiple Calls and test it within a sync and also an async MVC Action. You will see that some requests will never bring there response back and end up in a deadlock.

```
            var page = new ClientSidePage(ctx);
            var components = page.AvailableClientSideComponents();
```

#### Possible Fix

Use httpClient.SendAsync().ConfigureAwait(false) or use async all the way up the stack and let us call the async methods directly!

### PR DESCRIPTION
**Pull request by OliverZeiser**
… this one is using ExecuteQueryAsync now

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no - yes?
| New sample?      | no - yes?
| Related issues?  | fixes #1617 
#### What's in this Pull Request?
Fixed the new async ExecuteQueryImplementation to work with the new SynchronizationContextRemover

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi @OliverZeiser ,

The SynchronizationContextRemover is called from the main public method that then calls the ExecuteQueryImplementation private method. So there's not need to call it again in my view. Do you things not working without it?

**Comment by jansenbe** [comment]
FYI: I did try to use the provisioning engine from both a forms and a WPF app and got deadlocks...with the current dev version these resolved in my test scenario, but would be good if you could test your past deadlock scenarios as well

**Comment by OliverZeiser** [comment]
It is definitly not working in the current DEV Branch. I am using a MVC Application. I have created a new Pull Request that shows the change that is needed. With this change it is working for me. Maybe you can test that again...
The problem is only with the ExecuteQueryAsync now that got added. It looks like you forgot to add the new SynchronizationContextRemover  there. But this leads to big issues, since PnP calls the ExecuteQueryAsync now in the ExecuteQueryRetry via the ExecuteQueryImplementation which is used everywhere.
You have only added the SynchronizationContextRemover  to the ExecuteQueryRetryAsync.

**Comment by jansenbe** [comment]
Got it...did push in a change for this just now, meaning I'll close this PR. Thanks for the testing and let me know if you still see deadlocks in your testing

**Comment by biste5** [comment]
you didn't take my suggestion @jansenbe 
https://github.com/SharePoint/PnP-Sites-Core/commit/5dc3e51ebb66c4c55f6f059a2dae0de03a9891ed#r27972838

:(

**Comment by jansenbe** [comment]
@biste5 : happy to review your suggestion if you can indicate the current approach is still resulting in deadlocks or whether you think something is fundamentally wrong

**Comment by biste5** [comment]
@jansenbe 

There's extra overhead (tasks, and reference types in memory) generated at
[ClientContextExtensions.cs#L73-L78](https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs#L73-L78)

should just be
```c#
public static Task ExecuteQueryRetryAsync(this ClientRuntimeContext clientContext, int retryCount = 10, int delay = 500, string userAgent = null)
{
    return ExecuteQueryImplementation(clientContext, retryCount, delay, userAgent);
}
```

**Comment by jansenbe** [comment]
That's indeed cleaner and better. Did some testing with your code and did not see issues and will check-in this change. Would be good if @OliverZeiser could validate this scenario still works after this change

**Pull request closed without merging**
