### PR TITLE
Fix for https://github.com/SharePoint/PnP/issues/906

### PR DESCRIPTION
**Pull request by lsmithmier**
| Q               | A
| --------------- | ---
| Bug fix?        | Yes
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #906

#### What's in this Pull Request?
Lookup Site Fields were not properly setting the source field when they were created.
Added ListFieldToken and code to populate on capture and apply on application of template.

### CODE REVIEW

**Comment by lsmithmier** [comment]
Q	A
Bug fix?	Yes
New feature?	no
New sample?	no
Related issues?	fixes #892
What's in this Pull Request?

Logic in the WillProvision for ObjectSiteSecurity was backwards for HasUniqueRoleAssignments.

**Comment by lsmithmier** [comment]
Sorry, I got  two pull requests stuck into one and closed it all in one night.

**Comment by jansenbe** [comment]
Hey Larry, thanks for this change. Can you please share the template you used to test this? Will help with validating this and also will be useful to extend our test cases

**Comment by jansenbe** [comment]
Hey Larry,

I've been testing the OOB engine and I'm able to provision a lookup field, including multiple columns as shown in below screenshot:
image

This has been realized using the fields defined in this template: https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/field_add.xml

I'm closing this PR for now, if it's still not possible to correctly provision lookup fields using the approach mentioned above I would suggest to open a new PR, provide a clean repro and explain the used test environment.

**Pull request closed without merging**
