### PR TITLE
Update assemblies coming from SP 2013 August 2017 (KB3213571)

### PR DESCRIPTION
**Pull request by jensotto**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?

Update SharePoint 2013 assemblies from [August 1, 2017, update for SharePoint Server 2013 Client Components SDK (KB3213571)](https://support.microsoft.com/en-us/help/3213571/august-1-2017-update-for-sharepoint-server-2013-client-components-sdk)

### CODE REVIEW

**Comment by jensotto** [comment]
@VesaJuvonen Is there any reason why an updated CSOM can't bee included soon? Preferably a more recent version than this PR includes. There are no breaking changes so I can't see any reason for sticking with an older version of CSOM. This also goes for SP2016 CSOM assemblies.
There are many new CSOM methods that have been added since the version that currently is included with PnP-Sites-Core.

**Comment by tmeckel** [comment]
@jensotto checking on which PRs @VesaJuvonen got assigned you might draw the conclusion that the integration of those PRs is ... let's say ... unlikely ***LOL*** 

Therefore I have no great hope that my own PR #1994  will find its way into the master in the near future.

**Comment by VesaJuvonen** [comment]
FYI - We understand that this has been way too long for coming, but we are finally releasing new updated versions of oob NuGet packages, which will be set to May 2018 CU level for both SP2013 and SP2016. Will be addressing these issues noted in this PR. The update is coming on first days of 2019. More details soon.

**Comment by jensotto** [comment]
@VesaJuvonen Thank you for the update. This was great news.
I wonder if it's possible to also get an update out for the AppForSharePointWebToolkit NuGet package with a fix for the issue reported in sp-dev-docs: [TokenHelper in AppForSharePointWebToolkit fails to validate host URL with port number](https://github.com/SharePoint/sp-dev-docs/issues/1358)

**Comment by jansenbe** [comment]
Hi Jens, we've integrated the new newer CSOM versions in the dev branch and have removed the needed compiler directives. Will close this PR now. Feel free to create a new PR for the additional needed changes.

**Pull request closed without merging**
