### PR TITLE
Implement content type visibility in list new item button when provisioning or …

### PR DESCRIPTION
**Pull request by jensotto**
…updating lists.

Fix issues in setting default content type on list.
Add several helper methods for this functionality.
Mark old SetDefaultContentTypetoList methods as Obsolete. These had many issues.
Modified some unit tests to work on site collections with different language than english.

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
Added support for hiding and showing list content types in the new button.
Fixed issues when setting default content type on a list.
Combined code for modifying content types in ObjectListInstance.cs into a single method. This way it's easier to ensure that the same code (with some smal adjustments) )runs both for new lists and when updating lists.
Fixed some unit tests to work on site collection with different language than English.
Added unit tests for most of the code paths.

I have marked the problematic methods for setting default content type as Obsolete. I see that there are a lot of extensions methods that do modifications on list content types that are exposed on List and Web but not where it should be (ContentTypeCollection). I believe this is confusing and creates clutter and should be cleaned up in and so that the extension methods does not end up in all possible objects. What do you think?

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @jensotto, we'll process this asap.

**Comment by erwinvanhunen** [comment]
Hi Jens Otto!

Can you elaborate a bit more on where you think the existing methods had problems? It's a big thing to mark something as obsolete. We have a procedure in place for methods that are being marked as obsolete (we need to specify a 'end date' which is several months in the future etc.) that we need to follow, so before we go to an 'obsolete' marking we need to fully understand if the existing method cannot be rewritten instead, resulting in the same functionality without marking it as obsolete.

Thanks,

Erwin

**Comment by jensotto** [comment]
If you look at the comments of the methods I marked as obsolete it clearly states that: "Notice. Currently removes other content types from the list. Known issue"
In order to not break functionality that others might be using I have marked the methods as obsolete and implemented new methods that does the work properly. I don't see the problem with marking them as obsolete as nothing will change other than a compile time warning for those that still use it. They even get notified that there are a better implementation available. Wasn't this your concern in my other PR that you closed? It's up to the PnP team how to handle the ultimate removal of the obsolete methods. That needs to be planed for, but I don't agree with that when it comes to marking methods as obsolete when there are a justifiable reason.
In addition I don't see the benefit of adding the extension methods to every single possible SharePoint client object to expose the functionality. For instance there should be no need for a SetDefaultContentTypeToList extension method on the list. What if every extension method operated like this. Web or other objects would be polluted with extension methods.

Additionally I don't think the naming of the old methods where good enough. Why call it SetDefaultContentTypeToList when it's an extension method for the List object? It's given that you want to set the default content type to the list that you are operation on. Also as explained in the description and in the unit tests, there are a multitude of cases that the original method would mess up the content types on a list. Just try to run my tests with the current implementation of the provisioning engine. They all will fail.

**Comment by erwinvanhunen** [comment]
Thank you.

We discussed this PR and decide to merge after some refactoring. We retained some of the old methods (those available  as web extension methods) and I fixed some small typos. I also moved the deprecated code to the correct locations.

**Comment by jensotto** [comment]
Thank you @erwinvanhunen , but I don't understand why you want to keep the SetDefaultContentTypeToList extension methods. They add nothing to the framework and it makes no sense to have list content type modifications on the web object. This is especially true for the two methods that require a List object as one of the parameters. If you already have the list why not use the list directly instead of going via the web? This makes no sense and should be phased out from the framework.
In addition one of the methods might fail if the content type id is not already fetched from the server.

Those three remaining methods that I marked as obsolete is poorly designed and I believe the framework is better without them.

**Comment by jensotto** [comment]
@erwinvanhunen one more thing. Since you changed the old extension methods to use my new method instead of the problematic SetDefaultContentTypeToList method they previously used you effectively broke backwards compatibility. The old methods had side effects and problematic features that now has been removed. Users already using the old extension methods might find this change disruptive. I believe you should keep the original implementation as is and keep my recommendation to mark them all as obsolete.

**Comment by jensotto** [comment]
@erwinvanhunen as an example the old methods searched for child content types and didn't require the content type id to match exactly. This had issues as noted in the comment on the method now removed.

**Comment by jensotto** [comment]
Here is the comment I made on SetDefaultContentTypeToList

1. It messes up the existing order and visibility configuration for the folder/list
2. Even if the default sort order (no unique order set) or the existing unique sort order
   already has the specified content type set as default, this method unnecessarily 
   sets or updates the unique content type order.
3. Given a list with the picture content type added, and not the document content type (0x0101). 
   If a user tries to set the document content type as default using the document content type id,        
   then this code will incorrectly add the picture content type as the default content type.
   This happens because the code searches for ANY child content type of the specified content type id.
   The code should only allow exact content type id matches. 
   A check for a direct child could be implemented, but it increases the complexity. All similar
   methods should then also implement direct child capabilities, 
   which might not be possible in all cases and would confuse API users.
   Also, existing SharePoint CSOM methods does not implement a fallback to direct child content type functionality

**Comment by erwinvanhunen** [comment]
Some thoughts:

Because someone does not like a method signature or the location of the method in the framework, that unfortunately does not justify marking the method obsolete and/or introducing a change in the signature. We checked and the current method has been used throughout its current lifetime in over 1000 tenants. We have a framework to maintain that is used by thousands and thousands of applications.
And it seems that those developers were totally okay with the location and naming. 

Now, if the method has an issue (which it does), that's a different thing: we do think that that should be fixed. However, renaming it, for the sake of "I think it shouldn't be there, the naming is wrong" is not a strong enough argument. And sure, from an academic standpoint the method naming is maybe not correct. And sure, from an academic standpoint the location of the method might be wrong too. Unfortunate, but so be it. PnP Sites Core is close to 4 years old, if not older already, and there are things that can be better. But we have weigh off what the added value is of the rename. Does it -really- improve the development experience? I wonder... where as retaining the old name would at least not cause a disruption where developer would have to rewrite/refactor the code.

Nevertheless, we started to merge parts of your PR anyway, as we do appreciate your work. Another thing: please refrain from personal statements in the source code. Developers using the framework will never see those. Only, if you're lucky, they will be seen by the maintainers of the code. If you need to address specific topics, add them to the actual pull request form in github instead. The source code is not the location to make a point through remarks.

You bring up a valid additional remark with the changed behavior. We discussed this and we are as such okay with it this changed behavior. E.g. we will mark the old methods as obsolete, as per your original PR. As people have to refactor their code anyway within the coming 6 months (I will extend the default deprecation period from 3 to 6 months in this case due to the additional refactoring a developer might have to do), they will notice that the method behaves differently.  After my modified merge we noticed that you changed the behavior of the existing unit test, while retaining the original test name. This I modified, and copied your modified test code to a new unit test, and reverted the old unit test. This keeps the tests in place for the old (deprecated) methods, while testing the functionality as offered by those methods, and it adds new tests which focus on your added methods.

**Comment by jensotto** [comment]
I just want to highlight a few things:
I didn't change or rename the method signature. I created new methods with clearer meaning and hooked up to the correct class (List) and most importantly fixed issues in the old implementation. I believe cleaning up the API and doing housekeeping should be possible to do and is necessary in a any public API/framework, especially when it matures and has legacy code that might not have been the best design. Keep in mind that I am not talking about breaking backwards compatibility or introducing breaking changes. Marking items as obsolete is totally benign, and should not automatically result in a removal of the obsolete code. I can tell you that I have never introduced a breaking change in the framework assembly signature. I know that changes in or removal of public items will result in breaking changes and break backwards compatibility (implementation details in methods/properties are a different story).

Removal of obsolete code needs to be carefully planned for and I believe that you have a too aggressive approach for this. 3-6 months is probably too short time frame. In any case a set time window for removal is not a good approach. Changes that will result in breaking changes should never be done unless a new major version of the API/framework is released. This is how semantic versioning specify how major, minor and patch versioning should work. The obsolete methods could easily have lived on for at least a year or more, and at least not have been removed before the next major version or maybe even the next two major versions.

In PR #1567 I have proposed a change in the assembly versioning. This is necessary to be able to support the same extensibility handler over several releases of the core framework. For this to be successful it is vital that no breaking changes is made in the publicly exposed code of the framework. If not, there could be situations where runtime exceptions can occur. Therefore you should not target a specific date and rather target a specific major version when removing obsolete code. Of course this will only be important if PR #1567 is approved, but regardless I think that this should be considered as normal practice. Normally there should be no backwards compatibility breaking changes within the same major version.

Regarding the comments I made in the code I'm sorry for not initially including them in the PR. I intended to, but I guess I must have forgotten about that. Regardless I believe adding it as comments in the code was justified as I thought that the code would live on for a long time. It was therefore important to have the history of why the code was problematic close to the source code so that it would be easy for the maintainers or contributors to see. No one would go and look in my PR after a few months or a year.

**Comment by wobba** [comment]
@jensotto  I want to make a general comment. When wanting to fix a larger portion of PnP, and obsoleting things - it's a better approach to create an issue first and discuss how you want to change it, before moving ahead and writing lots of code which can be rejected. It makes the conversation that much more pleasant for everyone.

We don't want to fight about what goes in or out as PR's, and there are indeed discussions in the PnP team about PR's, especially ones like this which does a lot of change - and as @erwinvanhunen said, the changes are indeed valid.

As for naming, sometimes naming goes wrong or is not 100% semantic, but you have to live with it. There are SSOM methods still with spelling mistakes in them which will never be corrected. That's just how life is. It's better to solve concrete issues, instead of going all semantic and logic. Yes, we get it, no, we won't always listen and change - as change is always painful. It's the same as any dev team, how much effort do you put into housecleaning vs. new features - and don't get me wrong, there is room for both and is why PR's are always very welcome.

As for time something is obsolete before being removed even 3 months should be ok, and this is why. PnP is always build against the latest CSOM release which comes every month. That means, when you recompile you effectivly say you are fine with the latest version of SP - that be onprem or SPO. For SPO you don't really have a choice, and you can always stick to the version of PnP/CSOM you built with the first time. But if you want new features, you have to follow suit. If you want the latest PnP to work with whatever patch version you have on-prem, you have to build a version yourself linked to that specific CSOM version (as CSOM follows SSOM for onprem). If PnP were to maintain "proper" versioning linked to every single CSOM release - well, not going to happen :) So in that regards I would see PnP as a moving target on a month by month basis following CSOM - except CSOM never/seldom remove things as they are core API's - PnP are extensions basically.

So to end, we do appreciate your contributions, but focus more on fixing/adding functionality instead of debating naming etc. Keep a civil discussion tone and you are that much more likely to get your points through - and I've had my discussions with the PnP team as well. We do listen :)

**Comment by jensotto** [comment]
@wobba I think this is getting out of hand, and blown out of proportions. I don't think I had an uncivil discussion tone in the discussions, and if it was interpreted differently I apologies for that.

Basically what I have contributed is nothing more than fixing a long standing bug and troublesome implementation that was even noted as a limitation in the original implementation. As I saw there was no way to fix the existing implementation without affecting existing usage of it I thought it was best to mark those methods as obsolete. The fact that the naming and location of the extension methods were suboptimal was secondary to me, but I saw it as an opportunity to "clean up" in it as it's little use to have two similar parallell implementation left in the code simultaneously. I only wanted to point out to the PnP team that I thought that this clutters the framework.
Without doing this I would have felt uneasy with contributing as I would just add more clutter to the framework/extension methods. 
Are you saying that I can't propose changes like this in the future?

I'm not sure if I fully follow you on the versioning comments. I understand that new features are introduced in SPO very often, but I have never seen or encountered any breaking changes within a major version of SSOM/CSOM, and I would be surprised if there are many if any. As long as CSOM does not introduce any breaking changes there should be no problem for the PnP framework to avoid introducing breaking changes too. There is no need to link to a specific CSOM version as long as you are using the same version or a newer version. This is because CSOM releases does not introduce breaking changes in newer versions within the same major version.

**Comment by wobba** [comment]
@jensotto :) Proposes like this are very welcome indeed - but it's easier to merge if you discuss ways to implement it beforehand - as it eases merging. A good practice I've had success with in my work life and for larger PR's in PnP. "Does this sound like a smart approach if I fix it like A, B, C?".

And I do see your versioning points, but I don't agree CSOM is an example to necessarily follow, as nothing is cleared out due to SSOM dependencies and backwards compatibility. The most important reason for linking to a newer CSOM version is that PnP takes a dependency on new features released in CSOM - requiring a new version, and this happens just about every month - at least for SPO, which is the main build target.

**Pull request merged**
